ITEM.name = "Echo Detector";
ITEM.desc = "This dated anomalous activity detector produces an alarm signal when anomalous particles enter a special chamber as you approach an anomaly. It can also register the presence of artifacts and measure the distance to the nearest one. The distance is indicated by the frequency of the sound the detector emits. To switch to artifact search mode, open the device's front cover. Also includes a somehow unlimited supply of bolts."
ITEM.model = "models/kali/miscstuff/stalker/detector_echo.mdl";
ITEM.class = "detector_echo"
ITEM.category = "Detectors"
ITEM.weaponCategory = "detector"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 0.44
ITEM.price = 3460
ITEM.flag = "N"
