ITEM.name = "Veles Detector";
ITEM.desc = "A next generation scientific detection scanner. Thanks to three modernized detection chambers, the position of artifacts is shown on a special display screen. When closed, the device registers only radiation and anomalies. To switch to artifact search mode, open the front LED display. Also includes a somehow unlimited supply of bolts."
ITEM.model = "models/kali/miscstuff/stalker/detector_veles.mdl";
ITEM.class = "detector_veles"
ITEM.category = "Detectors"
ITEM.weaponCategory = "detector"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 0.29
ITEM.price = 46880
ITEM.flag = "E"
