ITEM.name = "Artifact Belt (3 Slot)"
ITEM.model = "models/weapons/w_defuser.mdl"
ITEM.desc = "An unprotected belt for holding three artifacts for use."
--ITEM.category = "Miscellaneous"
ITEM.flag = "N"
ITEM.price = 6000
ITEM.weight = 1.5
ITEM.width = 2
ITEM.height = 1
ITEM.isSafe = false
ITEM.contSlots = 3
