ITEM.name = "Artifact Belt (2 Slot)"
ITEM.model = "models/weapons/w_defuser.mdl"
ITEM.desc = "A small unprotected belt for holding two artifacts for use."
--ITEM.category = "Miscellaneous"
ITEM.flag = "N"
ITEM.price = 4000
ITEM.weight = 1
ITEM.width = 2
ITEM.height = 1
ITEM.isSafe = false
ITEM.contSlots = 2
