local PLUGIN = PLUGIN
--list of weps
PLUGIN.wepList = {
	--[[
    ["id"] = {
        name = "name",
        desc = "desc",
        price = 0,
        model = "model",
        width = 1,
		height = 1,
		category = "Weapons - Test",
        flag = "y",
        class = "class",
        weaponCategory = "primary", --or sidearm?
        magType = "",
		otherMagTypes = {["id"] = "name 1", ["id2"] = "name 2"}, --line can be removed, for returning use same key as magtype
		bodygroups = {[1] = 1, [4] = 5} --etc, apply on dropped model
	},
    ]]--types: ws n pistol shotgun
["wep_ak12"] = {
	name = "AK-12", --tier 5 rifle
	desc = "An assault rifle chambered in 5.45x39mm.",
	price = 36880,--3800,--2100, --1800, --889,
	model = "models/weapons/tfa_ins2/w_ak12.mdl",
	width = 4,
	height = 2,
	weight = 3.4,
	flag = "4",
	type = "n",
	category = "Weapons - Rifles",
	class = "tfa_ins2_ak12_sky",
	weaponCategory = "primary",
	magType = "mag_545ak",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_ak74"] = {
	name = "AK-74", --tier 3 rifle
	desc = "An assault rifle chambered in 5.45x39mm.",
	price = 26950,--3150,--2800,--1500,--950, --722,
	model = "models/weapons/tfa_ins2/akpack/w_ak74.mdl",
	width = 4,
	height = 2,
	weight = 3.3,
	flag = "2",
	type = "n",
	category = "Weapons - Rifles",
	class = "tfa_ins2_ak74_r_sky",
	weaponCategory = "primary",
	magType = "mag_545ak",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_akm"] = {
	name = "AKM", --tier 3 rifle
	desc = "An assault rifle chambered in 7.62x39mm.",
	price = 28780,--3500,--3100,--1700,--950, --722,
	model = "models/weapons/tfa_ins2/akpack/w_akm.mdl",
	width = 4,
	height = 2,
	weight = 3.5,
	flag = "2",
	type = "ws",
	category = "Weapons - Rifles",
	class = "tfa_ins2_akm_r_sky",
	weaponCategory = "primary",
	magType = "mag_762ak",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
--[[
["wep_an94"] = {
	name = "AN-94", --tier 3 rifle
	desc = "An assault rifle chambered in 5.45x39mm.",
	price = 4650,--3900,--1700,--950, --722,
	model = "models/weapons/tfa_ins2/w_abakan.mdl",
	width = 4,
	height = 2,
	weight = 6.83,
	flag = "3",
	type = "ws",
	category = "Weapons - Rifles",
	class = "tfa_ins2_abakan_sky",
	weaponCategory = "primary",
	magType = "mag_545ak",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
]]
["wep_aks"] = {
	name = "AKS-74U", --tier 3 rifle
	desc = "A compact assault rifle chambered in 5.45x39mm.",
	price = 15270,--2900,--2300,--1400,--750, --449,
	model = "models/weapons/tfa_ins2/akpack/w_aks74u.mdl",
	width = 3,
	height = 2,
	weight = 2.6,
	flag = "1",
	type = "n",
	category = "Weapons - Rifles",
	class = "tfa_ins2_aks_r_sky",
	weaponCategory = "primary",
	magType = "mag_545ak",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_aug"] = {
	name = "AUG A2", --tier 3 rifle
	desc = "A bullpup assault rifle chambered in 5.56x45mm.",
	price = 40680,--2700,--1500, --591,
	model = "models/weapons/tfa_ins2/w_aug.mdl",
	width = 4,
	height = 2,
	weight = 3.3,
	flag = "3",
	type = "n",
	category = "Weapons - Rifles",
	class = "tfa_ins2_aug_sky",
	weaponCategory = "primary",
	magType = "mag_aug",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_awm"] = {
	name = "AWM", --tier 5 sniper
	desc = "A high-powered sniper rifle in .338 Lapua Magnum.",
	price = 107500,--52000,--44000,--25000, --3406,
	model = "models/weapons/tfa_ins2/w_awm_l86a1.mdl",
	width = 6,
	height = 2,
	weight = 7,
	flag = "5",
	type = "ws",
	category = "Weapons - Snipers",
	class = "tfa_ins2_awm_sky",
	weaponCategory = "primary",
	magType = "ammo_338",
	disableChamber = true,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_deserteagle"] = {
	name = "Desert Eagle", --tier 1 pistol
	desc = "A large handgun chambered in .50 AE.",
	price = 19680,--1750,--850, --670-720, price online 2000,
	model = "models/weapons/tfa_ins2/w_deagle.mdl",
	width = 1,
	height = 1,
	weight = 2,
	flag = "3",
	type = "pistol",
	category = "Weapons - Pistols",
	class = "tfa_ins2_deagle_sky",
	weaponCategory = "sidearm",
	magType = "mag_deserteagle",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_famas"] = {
	name = "FAMAS F1", --tier 3 rifle
	desc = "A bullpup assault rifle chambered in 5.56x45mm.",
	price = 34900,--2600,--1500, --1210,
	model = "models/weapons/tfa_ins2/w_famas.mdl",
	width = 4,
	height = 2,
	weight = 3.8,
	flag = "2",
	type = "n",
	category = "Weapons - Rifles",
	class = "tfa_ins2_famas_sky",
	weaponCategory = "primary",
	magType = "mag_famas",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_g36c"] = {
	name = "H&K G36C", --tier 3 rifle
	desc = "An assault rifle chambered in 5.56x45mm.",
	price = 38950,--3300,--2900,--1600, --1403,
	model = "models/weapons/tfa_ins2/w_g36c.mdl",
	width = 4,
	height = 2,
	weight = 2.82,
	flag = "3",
	type = "n",
	category = "Weapons - Rifles",
	class = "tfa_ins2_g36c_sky",
	weaponCategory = "primary",
	magType = "mag_g36",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_glock"] = {
	name = "Glock 17", --tier 1 pistol
	desc = "A pistol in 9x19mm.",
	price = 8460,--670,--650,--300, --245, real life online: 500,
	model = "models/weapons/tfa_ins2/w_glock17.mdl",
	width = 1,
	height = 1,
	weight = 0.625,
	flag = "2",
	type = "pistol",
	category = "Weapons - Pistols",
	class = "tfa_ins2_glock17_sky",
	weaponCategory = "sidearm",
	magType = "mag_glock",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_glocka"] = {
	name = "Glock 17 AUTO", --tier 1 pistol
	desc = "A custom-made automatic pistol in 9x19mm.",
	price = 15460,--2500,--1650,--300, --245, real life online: 500,
	model = "models/weapons/tfa_ins2/w_glock17.mdl",
	width = 1,
	height = 1,
	weight = 0.71,
	flag = "m",
	type = "pistol",
	category = "Weapons - Pistols",
	class = "tfa_ins2_glock17a_sky",
	weaponCategory = "sidearm",
	magType = "mag_glock",
	disableChamber = false,
	noBusiness = true,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
--[[
["wep_cz75"] = {
	name = "CZ 75 B", --tier 1 pistol
	desc = "A pistol in 9x19mm.",
	price = 655,--640,--300, --245, real life online: 500,
	model = "models/weapons/tfa_ins2/w_cz75b.mdl",
	width = 1,
	height = 1,
	weight = 1.56,
	flag = "1",
	type = "pistol",
	category = "Weapons - Pistols",
	class = "tfa_ins2_cz75_sky",
	weaponCategory = "sidearm",
	magType = "mag_cz",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
]]
["wep_usp"] = {
	name = "H&K USP .45", --tier 1 pistol
	desc = "A pistol in .45 ACP.",
	price = 8660,--710,--340, --402, gunbroker ~875,
	model = "models/weapons/tfa_ins2/tiggsusp/w_usp.mdl",
	width = 1,
	height = 1,
	weight = 0.88,
	flag = "2",
	type = "pistol",
	category = "Weapons - Pistols",
	class = "tfa_ins2_tiggusp_sky",
	weaponCategory = "sidearm",
	magType = "mag_usp",
	--defaultMods = {},
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_usp9"] = {
	name = "H&K USP 9x19mm", --tier 1 pistol
	desc = "A pistol in 9x19mm.",
	price = 9040,--710,--340, --402, gunbroker ~875,
	model = "models/weapons/tfa_ins2/tiggsusp/w_usp.mdl",
	width = 1,
	height = 1,
	weight = 0.79,
	flag = "2",
	type = "pistol",
	category = "Weapons - Pistols",
	class = "tfa_ins2_tiggusp_sky",
	weaponCategory = "sidearm",
	magType = "mag_usp9",
	defaultMods = {[11] = "sky_usp_9mm",},
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_uspm"] = {
	name = "H&K USP Match", --tier 1 pistol
	desc = "A pistol in 9x19mm.",
	price = 9900,--710,--340, --402, gunbroker ~875,
	model = "models/weapons/tfa_ins2/tiggsusp/w_usp.mdl",
	width = 1,
	height = 1,
	weight = 1.2,
	flag = "2",
	type = "pistol",
	category = "Weapons - Pistols",
	class = "tfa_ins2_tiggusp_sky",
	weaponCategory = "sidearm",
	magType = "mag_usp9",
	defaultMods = {[11] = "sky_usp_9mm", [12] = "tfa_ins2_si_tiggsmatch"},
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_izh"] = {
	name = "Baikal IZH-43", --tier 1 shotgun
	desc = "A double barreled shotgun.",
	price = 11400,--1600,--600, --347?, estimated: 200-400,
	model = "models/weapons/tfa_ins2/w_doublebarrel_fix.mdl",
	width = 4,
	height = 1,
	weight = 3.2,
	flag = "1",
	type = "shotgun",
	category = "Weapons - Shotguns",
	class = "tfa_ins2_doublebarrel_sky",
	weaponCategory = "primary",
	magType = "ammo_buckshot",
	disableChamber = true,
	otherMagTypes = {["default"] = "Buckshot", ["sky_ammo_slug"] = "Slug", 
	["sky_ammo_frag"] = "Frag", ["sky_ammo_dragon"] = "Dragon's Breath",
	["sky_ammo_nslug"] = "NL Slug", }
},
["wep_izhsawn"] = {
	name = "Baikal IZH-43 (Sawn-off)", --tier 1 shotgun
	desc = "A sawn-off variation of a double barreled shotgun.",
	price = 8460,--1450,--1600,--600, --347?, estimated: 200-400,
	model = "models/weapons/tfa_ins2/w_sawedoff.mdl", --forgot to check if this has good physics
	width = 2,
	height = 1,
	weight = 2,
	flag = "1",
	type = "shotgun",
	category = "Weapons - Shotguns",
	class = "tfa_ins2_doublebarrelsawnoff_sky",
	weaponCategory = "sidearm",
	magType = "ammo_buckshot",
	disableChamber = true,
	otherMagTypes = {["default"] = "Buckshot", ["sky_ammo_slug"] = "Slug", 
	["sky_ammo_frag"] = "Frag", ["sky_ammo_dragon"] = "Dragon's Breath",
	["sky_ammo_nslug"] = "NL Slug", }
},
["wep_spas"] = {
	name = "SPAS-12", --tier 1 shotgun
	desc = "A pump action shotgun.",
	price = 20890,--2100,--1000, --347?, estimated: 200-400,
	model = "models/weapons/tfa_ins2/w_spas12_bri.mdl",
	width = 4,
	height = 1,
	weight = 4.1,
	flag = "3",
	type = "shotgun",
	category = "Weapons - Shotguns",
	class = "tfa_ins2_spas12_sky",
	weaponCategory = "primary",
	magType = "ammo_buckshot",
	disableChamber = true,
	otherMagTypes = {["default"] = "Buckshot", ["sky_ammo_slug"] = "Slug", 
	["sky_ammo_frag"] = "Frag", ["sky_ammo_dragon"] = "Dragon's Breath",
	["sky_ammo_nslug"] = "NL Slug", }
},
--[[
["wep_ksg"] = {
	name = "Kel-Tec KSG", --tier 1 shotgun
	desc = "A bullpup pump action shotgun.",
	price = 3050,--2400,--1200, --859, msrp on site 990,
	model = "models/weapons/tfa_ins2/w_ksg.mdl",
	width = 4,
	height = 1,
	weight = 6.9,
	flag = "1",
	type = "shotgun",
	category = "Weapons - Shotguns",
	class = "tfa_ins2_ksg_sky",
	weaponCategory = "primary",
	magType = "ammo_buckshot",
	disableChamber = true,
	otherMagTypes = {["default"] = "Buckshot", ["sky_ammo_slug"] = "Slug", 
	["sky_ammo_frag"] = "Frag", ["sky_ammo_dragon"] = "Dragon's Breath",
	["sky_ammo_nslug"] = "NL Slug", }
},
]]
["wep_m1014"] = {
	name = "Benelli M4 Super 90",--m1014", --tier 4 shotgun
	desc = "A semi-automatic shotgun.",
	price = 43400,--3000,--1500, --855/879,
	model = "models/weapons/tfa_ins2/w_m1014.mdl",
	width = 4,
	height = 1,
	weight = 3.82,
	flag = "4",
	type = "shotgun",
	category = "Weapons - Shotguns",
	class = "tfa_ins2_m1014_sky",
	weaponCategory = "primary",
	magType = "ammo_buckshot",
	disableChamber = true,
	otherMagTypes = {["default"] = "Buckshot", ["sky_ammo_slug"] = "Slug", 
	["sky_ammo_frag"] = "Frag", ["sky_ammo_dragon"] = "Dragon's Breath",
	["sky_ammo_nslug"] = "NL Slug", }
},
["wep_m1911"] = {
	name = "M1911", --tier 1 pistol
	desc = "A pistol chambered in .45 ACP.",
	price = 6560,--640,--280, --404,
	model = "models/weapons/tfa_ins2/w_m1911_fix.mdl",
	width = 1,
	height = 1,
	weight = 1.1,
	flag = "1",
	type = "pistol",
	category = "Weapons - Pistols",
	class = "tfa_ins2_m1911_sky",
	weaponCategory = "sidearm",
	magType = "mag_1911",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_m4a1"] = {
	name = "M4A1", --tier 2 rifle
	desc = "An assault rifle chambered in 5.56x45mm.",
	price = 29560,--2550,--1500, --570,
	model = "models/weapons/tfa_ins2/w_m4a1.mdl",
	width = 4,
	height = 2,
	weight = 2.9,
	flag = "2",
	type = "n",
	category = "Weapons - Rifles",
	class = "tfa_ins2_m4a1_sky",
	weaponCategory = "primary",
	magType = "mag_stanag",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
--[[
["wep_l85"] = {
	name = "L85A2", --tier 2 rifle
	desc = "An assault rifle chambered in 5.56x45mm.",
	price = 3200,--2600,--1500, --570,
	model = "models/weapons/tfa_ins2/w_l85a2.mdl",
	width = 4,
	height = 2,
	weight = 6.6,
	flag = "2",
	type = "n",
	category = "Weapons - Rifles",
	class = "tfa_ins2_l85a2_sky",
	weaponCategory = "primary",
	magType = "mag_stanag",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
]]
["wep_m590"] = {
	name = "Mossberg M590A1", --tier 1 shotgun
	desc = "A pump action shotgun.",
	price = 21450,--2200,--1100, --883, real life has msrp at 714,
	model = "models/weapons/tfa_ins2/w_m590_olli.mdl",
	width = 4,
	height = 1,
	weight = 3.3,
	flag = "2",
	type = "shotgun",
	category = "Weapons - Shotguns",
	class = "tfa_ins2_m590o_sky",
	weaponCategory = "primary",
	magType = "ammo_buckshot",
	disableChamber = true,
	otherMagTypes = {["default"] = "Buckshot", ["sky_ammo_slug"] = "Slug", 
	["sky_ammo_frag"] = "Frag", ["sky_ammo_dragon"] = "Dragon's Breath",
	["sky_ammo_nslug"] = "NL Slug", }
},
["wep_m9"] = {
	name = "Beretta M92FS", --tier 1 pistol
	desc = "A pistol chambered in 9x19mm.",
	price = 5520,--650,--290, --245?,
	model = "models/weapons/tfa_ins2/w_m9.mdl",
	width = 1,
	height = 1,
	weight = 0.95,
	flag = "1",
	type = "pistol",
	category = "Weapons - Pistols",
	class = "tfa_ins2_m9_sky",
	weaponCategory = "sidearm",
	magType = "mag_m9",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_para"] = {
	name = "Minimi Para", --tier 4 mg
	desc = "A light machine gun chambered in 5.56x45mm.",
	price = 56580,--18500,--18000,--9200, --1626,
	model = "models/weapons/tfa_ins2/w_minimi.mdl",
	width = 5,
	height = 2,
	weight = 7.68,
	flag = "4",
	type = "n",
	category = "Weapons - MGs",
	class = "tfa_ins2_minimi_sky",
	weaponCategory = "primary",
	magType = "mag_minimi",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
--[[
["wep_mk18"] = {
	name = "MK18", --tier 4 rifle
	desc = "An assault rifle chambered in 5.56x45mm.",
	price = 4100,--3200,--1900, --878 just used sopmod idk, price on site 2000,
	model = "models/weapons/tfa_ins2/w_mk18.mdl",
	width = 4,
	height = 2,
	weight = 6.0,
	flag = "2",
	type = "n",
	category = "Weapons - Rifles",
	class = "tfa_ins2_mk18_sky",
	weaponCategory = "primary",
	magType = "mag_stanag",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
]]
["wep_mp5"] = {
	name = "H&K MP5A4", --tier 2 smg
	desc = "A SMG chambered in 9x19mm.",
	price = 17680,--1400,--510, --378,
	model = "models/weapons/fas2wm/smgs/w_mp5.mdl", --uh bgs?
	width = 3,
	height = 2,
	weight = 2.8,
	flag = "1",
	type = "pistol",
	category = "Weapons - SMGs",
	class = "tfa_fas2_mp5_sky",
	weaponCategory = "primary",
	magType = "mag_mp5",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_mp5k"] = {
	name = "H&K MP5KA4", --tier 2 smg
	desc = "A SMG chambered in 9x19mm.",
	price = 15800,--1360,--490, --303,
	model = "models/weapons/fas2wm/smgs/w_mp5.mdl",
	width = 2,
	height = 2,
	weight = 1.9,
	flag = "1",
	type = "pistol",
	category = "Weapons - SMGs",
	class = "tfa_fas2_mp5_sky",
	defaultMods = {[14] = "fas2tfa_mp5_pdw", [13] = ""}, --might work?
	weaponCategory = "sidearm",
	magType = "mag_mp5",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_mp5sd"] = {
	name = "H&K MP5SD4", --tier 2 smg
	desc = "A SMG chambered in 9x19mm.",
	price = 18800,--1360,--490, --303,
	model = "models/weapons/fas2wm/smgs/w_mp5.mdl",
	width = 2,
	height = 2,
	weight = 3.1,
	flag = "2",
	type = "pistol",
	category = "Weapons - SMGs",
	class = "tfa_fas2_mp5_sky",
	defaultMods = {[14] = "fas2tfa_mp5_sd", [1] = "ins2_br_supp_9mm"}, --might work?
	cantDetach = {[1] = true},
	weaponCategory = "primary",
	magType = "mag_mp5",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
--[[
["wep_msr"] = {
	name = "Remington MSR", --tier 4 sniper
	desc = "A sniper rifle chambered in 7.62x51mm NATO.",
	price = 31000,--26500,--13000, --not on site, over 10k all i can find,
	model = "models/weapons/tfa_ins2/w_codol_msr.mdl",
	width = 6,
	height = 2,
	weight = 13,
	flag = "3",
	type = "ws",
	category = "Weapons - Snipers",
	class = "tfa_ins2_codol_msr_sky",
	weaponCategory = "primary",
	magType = "ammo_762x51",
	disableChamber = true,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
]]
["wep_rpk"] = {
	name = "RPK", --tier 3 mg
	desc = "A light machine gun chambered in 7.62x39mm.",
	price = 39500,--18000,--8000, --2012,
	model = "models/weapons/tfa_ins2/akpack/w_rpk.mdl",
	width = 5,
	height = 2,
	weight = 4.8,
	flag = "3",
	type = "ws",
	category = "Weapons - MGs",
	class = "tfa_ins2_rpk_r_sky",
	weaponCategory = "primary",
	magType = "mag_rpk",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_ump"] = {
	name = "H&K UMP45", --tier 3 smg
	desc = "A SMG chambered in .45 ACP.",
	price = 27980,--1600,--580, --623,
	model = "models/weapons/tfa_ins2/w_ump45.mdl",
	width = 3,
	height = 2,
	weight = 2.48,
	flag = "2",
	type = "pistol",
	category = "Weapons - SMGs",
	class = "tfa_ins2_ump45_sky",
	weaponCategory = "primary",
	magType = "mag_ump",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_kriss"] = {
	name = "KRISS Vector", --tier 3 smg
	desc = "A SMG chambered in .45 ACP.",
	price = 26300,--1700,--580, --623,
	model = "models/weapons/tfa_ins2/w_krissv.mdl",
	width = 3,
	height = 2,
	weight = 2.7,
	flag = "3",
	type = "pistol",
	category = "Weapons - SMGs",
	class = "tfa_ins2_krissv_sky",
	weaponCategory = "primary",
	magType = "mag_kriss",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_m49mm"] = {
	name = "M4 9mm", --tier 2 smg
	desc = "A modified M4 that is now chambered in 9x19mm.",
	price = 32800,--2100,--800,
	model = "models/weapons/tfa_ins2/w_m4_9mm.mdl",
	width = 3,
	height = 2,
	weight = 2.7,
	flag = "3",
	type = "pistol",
	category = "Weapons - SMGs",
	class = "tfa_ins2_m4_9mm_sky",
	weaponCategory = "primary",
	magType = "mag_9mm32",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_mp443"] = {
	name = "MP443 Grach", --tier 1 pistol
	desc = "A pistol chambered in 9x19mm.",
	price = 7580, --245?,
	model = "models/weapons/tfa_ins2/mp443/w_mp443.mdl",
	width = 1,
	height = 1,
	weight = 0.95,
	flag = "1",
	type = "pistol",
	category = "Weapons - Pistols",
	class = "tfa_ins2_mp443_sky",
	weaponCategory = "sidearm",
	magType = "mag_mp443",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
--[[
["wep_rfb"] = {
	name = "Kel-Tec RFB", --tier 4 sniper
	desc = "A bullpup semi-automatic rifle chambered in 7.62x51mm NATO.",
	price = 14500,--8000,--2200, --1334,
	model = "models/weapons/tfa_ins2/w_rfb.mdl",
	width = 5,
	height = 2,
	flag = "2",
	type = "ws",
	category = "Weapons - Rifles",
	class = "tfa_ins2_rfb_sky",
	weaponCategory = "primary",
	magType = "mag_rfb",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},]]
["wep_evo"] = {
	name = "CZ Scorpion Evo 3", --tier 3 smg
	desc = "A SMG chambered in 9x19mm.",
	price = 25500,--2000,--790, --623,
	model = "models/weapons/tfa_ins2/w_scorpion_evo.mdl",
	width = 3,
	height = 2,
	weight = 2.82,
	flag = "2",
	type = "pistol",
	category = "Weapons - SMGs",
	class = "tfa_ins2_sc_evo_sky",
	weaponCategory = "primary",
	magType = "mag_evo",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},--[[
["wep_spectre"] = {
	name = "Spectre M4", --tier 2 smg
	desc = "A SMG chambered in 9x19mm.",
	price = 2250,--1800,--660,
	model = "models/weapons/tfa_ins2/w_spectre.mdl",
	width = 3,
	height = 2,
	flag = "1",
	type = "pistol",
	category = "Weapons - SMGs",
	class = "tfa_ins2_spectre_sky",
	weaponCategory = "primary",
	magType = "mag_spectre",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_acrcqb"] = {
	name = "ACR CQB", --tier 4 rifle
	desc = "An assault rifle chambered in 5.56x45mm.",
	price = 3100,--2600,--1600, --878 just used sopmod idk, price on site 2000,
	model = "models/weapons/tfa_ins2/w_acr_cqb.mdl",
	width = 4,
	height = 2,
	type = "n",
	flag = "2",
	category = "Weapons - Rifles",
	class = "tfa_ins2_acr_cqb_sky",
	weaponCategory = "primary",
	magType = "mag_stanag",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_px4"] = {
	name = "Beretta PX4", --tier 1 pistol
	desc = "A pistol chambered in 9x19mm.",
	price = 640,--620,--280, --245?,
	model = "models/weapons/tfa_ins2/w_beretta_px4_storm.mdl",
	width = 1,
	height = 1,
	flag = "1",
	type = "pistol",
	category = "Weapons - Pistols",
	class = "tfa_ins2_beretta_px4_sky",
	weaponCategory = "sidearm",
	magType = "mag_px4",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},]]
["wep_knw"] = {
	name = "Kimber Night Warrior", --tier 1 pistol
	desc = "A pistol chambered in .45 ACP.",
	price = 8860,--660,--310, --245?,
	model = "models/weapons/w_nb_ins_knw.mdl",
	width = 1,
	height = 1,
	weight = 1.07,
	flag = "1",
	type = "pistol",
	category = "Weapons - Pistols",
	class = "tfa_ins2_knw_sky",
	weaponCategory = "sidearm",
	magType = "mag_1911",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},--[[
["wep_m500"] = {
	name = "Mossberg M500", --tier 1 shotgun
	desc = "A pump action shotgun with no stock.",
	price = 2700,--2000,--1000, --1284, price on site 459,
	model = "models/weapons/tfa_ins2/w_m500.mdl",
	width = 3,
	height = 1,
	flag = "1",
	type = "shotgun",
	category = "Weapons - Shotguns",
	class = "tfa_ins2_m500_sky",
	weaponCategory = "primary",
	magType = "ammo_buckshot",
	disableChamber = true,
	otherMagTypes = {["default"] = "Buckshot", ["sky_ammo_slug"] = "Slug", 
	["sky_ammo_frag"] = "Frag", ["sky_ammo_dragon"] = "Dragon's Breath",
	["sky_ammo_nslug"] = "NL Slug", }
},
["wep_r870mcs"] = {
	name = "Remington 870 MCS", --tier 2 shotgun
	desc = "A pump action shotgun.",
	price = 2950,--2400,--1300, --1284, price on site 459,
	model = "models/weapons/tfa_ins2/w_r870mcs.mdl",
	width = 4,
	height = 1,
	weight = 8,
	flag = "2",
	type = "shotgun",
	category = "Weapons - Shotguns",
	class = "tfa_ins2_r870mcs_sky",
	weaponCategory = "primary",
	magType = "ammo_buckshot",
	disableChamber = true,
	otherMagTypes = {["default"] = "Buckshot", ["sky_ammo_slug"] = "Slug", 
	["sky_ammo_frag"] = "Frag", ["sky_ammo_dragon"] = "Dragon's Breath",
	["sky_ammo_nslug"] = "NL Slug", }
},
["wep_saigry"] = {
	name = "SAI GRY SBR", --tier 5 rifle
	desc = "An assault rifle chambered in 5.56x45mm.",
	price = 4100,--3600,--2500, 
	model = "models/weapons/tfa_ins2/w_sai_gry.mdl",
	width = 4,
	height = 2,
	type = "n",
	flag = "3",
	category = "Weapons - Rifles",
	class = "tfa_ins2_sai_gry_sky",
	weaponCategory = "primary",
	magType = "mag_stanag",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_scarh"] = {
	name = "FN SCAR-H", --tier 4 rifle
	desc = "A battle rifle chambered in 7.62x51mm NATO.",
	price = 4000,--3200,--2200, --878 just used sopmod idk, price on site 2000,
	model = "models/weapons/tfa_ins2/w_scarh.mdl",
	width = 4,
	height = 2,
	flag = "3",
	type = "ws",
	category = "Weapons - Rifles",
	class = "tfa_ins2_scarh_sky",
	weaponCategory = "primary",
	magType = "mag_scarh",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
]]
--[[
["wep_wa2000"] = {
	name = "Walther WA 2000", --tier 4 sniper
	desc = "A semi-automatic bullpup sniper rifle.",
	price = 90000,--65000, --1334, --THIS IS APPARENTLY REALLY RARE LOL
	model = "models/weapons/tfa_ins2/w_wa2000.mdl",
	width = 5,
	height = 2,
	weight = 8.6,
	flag = "m",
	type = "ws",
	category = "Weapons - Snipers",
	class = "tfa_ins2_wa2000_sky",
	weaponCategory = "primary",
	magType = "mag_wa2000",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},]]
["wep_lr300"] = {
	name = "ZM LR-300", --tier 3 rifle
	desc = "An assault rifle chambered in 5.56x45mm.",
	price = 26480,--2600,--1500, 
	model = "models/weapons/tfa_ins2/w_zm_lr300.mdl",
	width = 4,
	height = 2,
	weight = 3.1,
	flag = "2",
	type = "n",
	category = "Weapons - Rifles",
	class = "tfa_ins2_zm_lr300_sky",
	weaponCategory = "primary",
	magType = "mag_stanag",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_fn2000"] = {
	name = "FN-2000", --tier 3 rifle
	desc = "A bullpup assault rifle chambered in 5.56x45mm.",
	price = 45880,--2800,--1700, 
	model = "models/weapons/tfa_ins2/fn_2000/w_fn_2000.mdl",
	width = 4,
	height = 2,
	weight = 3.8,
	flag = "4",
	type = "n",
	category = "Weapons - Rifles",
	class = "tfa_ins2_fn_2000_sky",
	weaponCategory = "primary",
	magType = "mag_stanag",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_val"] = {
	name = "AS Val",
	desc = "An assault rifle with an integrated suppressor chambered in 9x39mm.",
	price = 38860,--2800,--1700, 
	model = "models/weapons/tfa_ins2/w_asval.mdl",
	width = 4,
	height = 2,
	weight = 2.5,
	flag = "3",
	type = "ws", --todo what repairs this in stalker??
	category = "Weapons - Rifles",
	class = "tfa_ins2_asval_sky",
	weaponCategory = "primary",
	magType = "mag_val",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},--[[
["wep_fal"] = {
	name = "FN Fal", --tier 3 rifle
	desc = "An automatic rifle chambered in 7.62x51mm NATO.",
	price = 5200,--2800,--1700, 
	model = "models/weapons/tfa_ins2/w_fal.mdl",
	width = 4,
	height = 2,
	flag = "2",
	type = "ws",
	category = "Weapons - Rifles",
	class = "tfa_ins2_fnfal_sky",
	weaponCategory = "primary",
	magType = "mag_fal",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_galil"] = {
	name = "IMI Galil", --tier 3 rifle
	desc = "An assault rifle chambered in 5.56x45mm.",
	price = 4000,--2800,--1700, 
	model = "models/weapons/tfa_ins2/w_galil.mdl",
	width = 4,
	height = 2,
	flag = "2",
	type = "n",
	category = "Weapons - Rifles",
	class = "tfa_ins2_galil_sky",
	weaponCategory = "primary",
	magType = "mag_galil",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},]]
["wep_m40"] = {
	name = "M40A1", --tier 3 rifle
	desc = "A sniper rifle chambered in 7.62x51mm NATO.",
	price = 40500,--2800,--1700, 
	model = "models/weapons/tfa_ins2/w_m40a1.mdl",
	width = 4,
	height = 1,
	weight = 6.6,
	flag = "2",
	type = "ws",
	category = "Weapons - Snipers",
	class = "tfa_ins2_m40a1_sky",
	weaponCategory = "primary",
	magType = "ammo_762x51",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_mosin"] = {
	name = "Mosin-Nagant M91", --tier 3 rifle
	desc = "A sniper rifle chambered in 7.62x54mmR.",
	price = 10260,--2800,--1700, 
	model = "models/weapons/tfa_ins2/w_mosin.mdl",
	width = 4,
	height = 1,
	weight = 4.9,
	flag = "1",
	type = "ws",
	category = "Weapons - Snipers",
	class = "tfa_ins2_mosin_sky",
	weaponCategory = "primary",
	magType = "ammo_762x54",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_pkp"] = {
	name = "PKP Pecheneg", --tier 3 rifle
	desc = "A light machine gun chambered in 7.62x54mmR.",
	price = 90850,--2800,--1700, 
	model = "models/weapons/tfa_ins2/w_pkm.mdl",
	width = 6,
	height = 5,
	weight = 7.5,
	flag = "4",
	type = "ws",
	category = "Weapons - MGs",
	class = "tfa_ins2_pkp_sky",
	weaponCategory = "primary",
	magType = "mag_pkp",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_pm"] = {
	name = "Makarov PM", --tier 3 rifle
	desc = "A pistol chambered in 9x18mm.",
	price = 4800,--2800,--1700, 
	model = "models/weapons/tfa_ins2/w_pm.mdl",
	width = 1,
	height = 1,
	weight = 0.73,
	flag = "1",
	type = "pistol",
	category = "Weapons - Pistols",
	class = "tfa_ins2_pm_sky",
	weaponCategory = "sidearm",
	magType = "mag_pm",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"},
	iconCam = {
		pos = Vector(0.60000002384186, 200, -0.30000001192093),
		ang = Angle(0, 270, 0),
		fov = 3,
	},
},
--[[
["wep_scarl"] = {
	name = "FN SCAR-L", --tier 3 rifle
	desc = "An assault rifle chambered in 5.56x45mm.",
	price = 4200,--2800,--1700, 
	model = "models/weapons/tfa_ins2/w_scarL.mdl",
	width = 4,
	height = 2,
	flag = "2",
	type = "n",
	category = "Weapons - Rifles",
	class = "tfa_ins2_scarl_sky",
	weaponCategory = "primary",
	magType = "mag_stanag",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_uzi"] = {
	name = "IMI UZI", --tier 3 rifle
	desc = "A submachine gun chambered in 9x19mm.",
	price = 190,--2800,--1700, 
	model = "models/weapons/tfa_ins2/w_uzi.mdl",
	width = 3,
	height = 2,
	flag = "1",
	type = "pistol",
	category = "Weapons - SMGs",
	class = "tfa_ins2_uzi_sky",
	weaponCategory = "primary",
	magType = "mag_uzi",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
]]
["wep_p226"] = {
	name = "P226", --tier 3 rifle
	desc = "A pistol chambered in 9x19mm.",
	price = 9980,--2800,--1700, 
	model = "models/weapons/fas2wm/pistols/w_p226.mdl",
	width = 1,
	height = 1,
	weight = 0.81,
	flag = "1",
	type = "pistol",
	category = "Weapons - Pistols",
	class = "tfa_fas2_p226_sky",
	weaponCategory = "sidearm",
	magType = "mag_p226",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_g3"] = {
	name = "G3", --tier 3 rifle
	desc = "A rifle chambered in 7.62x51mm.",
	price = 43500,--2800,--1700, 
	model = "models/weapons/fas2wm/rifles/w_g3.mdl",
	width = 4,
	height = 2,
	weight = 4.7,
	flag = "3",
	type = "ws",
	category = "Weapons - Rifles",
	class = "tfa_fas2_g3_sky",
	weaponCategory = "primary",
	magType = "mag_g3",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_ks23"] = {
	name = "KS23", --tier 3 rifle
	desc = "A shotgun chambered in 23mm.",
	price = 62800,--2800,--1700, 
	model = "models/weapons/fas2wm/shotguns/ks23_wm.mdl",
	width = 4,
	height = 1,
	weight = 3.85,
	flag = "5",
	type = "shotgun",
	category = "Weapons - Shotguns",
	class = "tfa_fas2_ks23_sky",
	weaponCategory = "primary",
	magType = "ammo_23",
	disableChamber = false,
	--default buckshot, slug, smoke, flashbang
	otherMagTypes = {["default"] = "Buckshot", ["sky_ammo_slug"] = "Slug", 
	--[[["sky_ammo_frag"] = "Frag", ["sky_ammo_dragon"] = "Dragon's Breath",
	["sky_ammo_nslug"] = "NL Slug",]] }
},
["wep_sg550"] = {
	name = "SIG SG550", --tier 3 rifle
	desc = "A rifle chambered in 5.56x45mm.",
	price = 43580,--2800,--1700, 
	model = "models/weapons/fas2wm/rifles/w_sg55x.mdl",
	width = 4,
	height = 2,
	weight = 4.1,
	flag = "3",
	type = "n",
	category = "Weapons - Rifles",
	class = "tfa_fas2_sg55x_sky",
	weaponCategory = "primary",
	magType = "mag_sg55x",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_sg553"] = {
	name = "SIG SG553", --tier 3 rifle
	desc = "A rifle chambered in 5.56x45mm.",
	price = 32580,--2800,--1700, 
	model = "models/weapons/fas2wm/rifles/w_sg55x.mdl",
	width = 4,
	height = 2,
	weight = 3.2,
	flag = "3",
	type = "n",
	category = "Weapons - Rifles",
	class = "tfa_fas2_sg55x_sky",
	weaponCategory = "primary",
	magType = "mag_sg55x",
	disableChamber = false,
	defaultMods = {[14] = "fas2tfa_sg550_cqb"}, --might work?
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},	
--[[ --kinda useless ngl, and also apparently no longer in production
["wep_sg5501"] = {
	name = "SIG SG550-1", --tier 3 rifle
	desc = "An automatic sniper chambered in 5.56x45mm.",
	price = 600,--2800,--1700, 
	model = "models/weapons/fas2wm/rifles/w_sg55x.mdl",
	width = 4,
	height = 2,
	flag = "1",
	type = "n",
	category = "Weapons - Sniper",
	class = "tfa_fas2_sg55x_sky",
	weaponCategory = "primary",
	magType = "mag_sg55x",
	disableChamber = false,
	defaultMods = {[14] = "fas2tfa_sg550_cqb",[7] = "fas2tfa_sg55x_scope", [13] = "fas2tfa_sg550_prstock"},
	cantDetach = {[7] = true},
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},]]
["wep_sks"] = {
	name = "SKS", --tier 3 rifle
	desc = "A rifle chambered in 7.62x39mm.",
	price = 18580,--2800,--1700, 
	model = "models/weapons/fas2wm/rifles/w_sks.mdl",
	width = 4,
	height = 1,
	weight = 3.75,
	flag = "1",
	type = "ws",
	category = "Weapons - Rifles",
	class = "tfa_fas2_sks_sky",
	weaponCategory = "primary",
	magType = "mag_sksclip",
	disableChamber = true,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_sksa"] = { --hide?
	name = "SKS Auto", --tier 3 rifle
	desc = "A custom automatic rifle chambered in 7.62x39mm using a detachable 20 round mag.",
	price = 28400,--2800,--1700, 
	model = "models/weapons/fas2wm/rifles/w_sks.mdl",
	width = 4,
	height = 2,
	weight = 3.71,
	flag = "2",
	type = "ws",
	category = "Weapons - Rifles",
	class = "tfa_fas2_sks_sky",
	weaponCategory = "primary",
	magType = "mag_sks20",
	disableChamber = true,
	defaultMods = {[15] = "fas2tfa_sks_20rnd",[16] = "fas2tfa_sks_bf"},
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_svd"] = {
	name = "SVD", --tier 3 rifle
	desc = "A rifle chambered in 7.62x54mmR.",
	price = 62550,--2800,--1700, 
	model = "models/weapons/fas2wm/rifles/w_svd.mdl",
	width = 5,
	height = 2,
	weight = 3.91,
	flag = "4",
	type = "ws",
	category = "Weapons - Snipers",
	class = "tfa_fas2_svd_sky",
	weaponCategory = "primary",
	magType = "mag_svd",
	disableChamber = true,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_acr"] = {
	name = "Remington ACR", --tier 4 rifle
	desc = "An assault rifle chambered in 5.56x45mm.",
	price = 42500,--2600,--1600, --878 just used sopmod idk, price on site 2000,
	model = "models/weapons/tfa_ins2/w_acr.mdl",
	width = 4,
	height = 2,
	weight = 3.6,
	type = "n",
	flag = "3",
	category = "Weapons - Rifles",
	class = "tfa_ins2_acr_sky",
	weaponCategory = "primary",
	magType = "mag_stanag",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
--[[
["wep_ar2"] = {
	name = "AR2", --tier 3 smg
	desc = "A rifle chambered in idktemp.",
	price = 250,--1600,--580, --623,
	model = "models/weapons/w_irifle.mdl",
	width = 3,
	height = 2,
	weight = 2.5,
	flag = "2",
	type = "combine",
	category = "Weapons - Combine",
	class = "tfa_mmod_ar2_sky",
	weaponCategory = "primary",
	magType = "mag_ar2",
	disableChamber = false,
	biolock = true,
	--otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},
["wep_ar3"] = {
	name = "AR3", --tier 3 smg
	desc = "A disposable MG chambered in idktemp.",
	price = 750,--1600,--580, --623,
	model = "models/weapons/tfa_mmod/w_ar3.mdl",
	width = 3,
	height = 2,
	weight = 2.5,
	flag = "2",
	type = "combine",
	category = "Weapons - Combine",
	class = "tfa_mmod_ar3_sky",
	weaponCategory = "primary",
	magType = "notactuallyanitem",
	disableChamber = false,
	cantBeUnloaded = true,
	defaultAmmo = 200,
	biolock = true,
	--otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"}
},]]
--modular guns
--[[
["wep_akx"] = {
	name = "AKX temp name", --tier 3 rifle
	desc = RarityText(RARITY_UNCOMMON).."An assault rifle chambered in 5.45x39mm.",
	price = 3150,--2800,--1500,--950, --722,
	model = "models/sky/weapons/w_akx.mdl",
	width = 4,
	height = 2,
	weight = 6.83,
	flag = "2",
	type = "n",
	category = "Weapons - Rifles",
	class = "tfa_ins2_akx_sky",
	weaponCategory = "primary",
	magType = "mag_akx",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"},
	convMagNames = {
		["mod_akx_conv_drum"] = "AKX Drum Magazine",
		["mod_akx_conv_snip"] = "AKX Sniper Magazine",
		["mod_akx_conv_spec"] = "HKX Magazine",
	},
	convMagTypes = {
		["mod_akx_conv_drum"] = "mag_akx_drum",
		["mod_akx_conv_snip"] = "mag_akx_snip",
		["mod_akx_conv_spec"] = "mag_hkx",
	},
	--defaultMods = {},
	iconCam = {	
		pos = Vector(-1.158297419548, -41.316745758057, -1.478454709053),
		ang = Angle(0, 90, 0),
		entAng = Angle(0, 0, 0),
		fov = 45,
		outline = true,
		outlineColor = RARITY_COLORS[RARITY_UNCOMMON],
	},
},
["wep_hkx"] = {
	name = "HKX temp name", --tier 3 rifle
	desc = RarityText(RARITY_UNCOMMON).."An assault rifle chambered in 5.56x45mm.",
	price = 3150,--2800,--1500,--950, --722,
	model = "models/sky/weapons/w_hkx.mdl",
	width = 4,
	height = 2,
	weight = 6.83,
	flag = "2",
	type = "n",
	category = "Weapons - Rifles",
	class = "tfa_ins2_hkx_sky",
	weaponCategory = "primary",
	magType = "mag_hkx",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"},
	convMagNames = {
		["mod_hkx_conv_drum"] = "HKX Drum Magazine",
		["mod_hkx_conv_snip"] = "HKX Sniper Magazine",
	},
	convMagTypes = {
		["mod_hkx_conv_drum"] = "mag_hkx_drum",
		["mod_hkx_conv_snip"] = "mag_hkx_snip",
	},
	--defaultMods = {},
	iconCam = {	
		pos = Vector(-1.158297419548, -41.316745758057, -1.478454709053),
		ang = Angle(0, 90, 0),
		entAng = Angle(0, 0, 0),
		fov = 49.265,
		outline = true,
		outlineColor = RARITY_COLORS[RARITY_UNCOMMON],
	},
},
["wep_macx"] = {
	name = "MACX temp name", --tier 3 rifle
	desc = RarityText(RARITY_UNCOMMON).."A submachine gun chambered in 9x19mm.",
	price = 3150,--2800,--1500,--950, --722,
	model = "models/sky/weapons/w_mac.mdl",
	width = 2,
	height = 2,
	weight = 6.83,
	flag = "1",
	type = "pistol",
	category = "Weapons - SMGs",
	class = "tfa_ins2_macx_sky",
	weaponCategory = "primary",
	magType = "mag_mac",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"},
	convMagNames = {
		["mod_mac_conv_hbm"] = "MAC .45 Magazine",
	},
	convMagTypes = {
		["mod_mac_conv_hbm"] = "mag_mac45",
	},
	--defaultMods = {},
	iconCam = {	
		pos = Vector(-5.1855640411377, -20.303838729858, -3.2192025184631),
		ang = Angle(0, 90, 0),
		entAng = Angle(0, 0, 0),
		fov = 45,
		outline = true,
		outlineColor = RARITY_COLORS[RARITY_UNCOMMON],
	},
},
["wep_pistolx"] = {
	name = "HS2100 TEMP", --tier 3 rifle
	desc = RarityText(RARITY_COMMON).."A pistol chambered in 9x19mm.",
	price = 3150,--2800,--1500,--950, --722,
	model = "models/sky/weapons/w_pistol.mdl",
	width = 1,
	height = 1,
	weight = 6.83,
	flag = "1",
	type = "pistol",
	category = "Weapons - Pistols",
	class = "tfa_ins2_pistolx_sky",
	weaponCategory = "primary",
	magType = "mag_pistolx",
	disableChamber = false,
	otherMagTypes = {["default"] = "Normal", ["sky_ammo_hp"] = "Hollow Point", ["sky_ammo_ap"] = "Armor Piercing"},
	convMagNames = {
		["mod_pis_conv_bm"] = "HS2100 Extended Magazine",
	},
	convMagTypes = {
		["mod_pis_conv_bm"] = "mag_pistolx_ext",
	},
	--defaultMods = {},
	iconCam = {	
		pos = Vector(-0.33122479915619, -12.628011703491, -2.6955764293671),
		ang = Angle(0, 90, 0),
		entAng = Angle(0, 0, 0),
		fov = 45,
		outline = true,
		outlineColor = RARITY_COLORS[RARITY_COMMON],
	},
},
]]
}

--list of mags
PLUGIN.magList = {
	--[[
    ["id"] = {
        name = "name",
        desc = "desc",
        price = 0,
        model = "model",
        width = 1,
        height = 1,
        flag = "y",
        ammoBox = false, --ammoBox makes empty items be removed
        ammoType = "skyammo", --the ammo type to give
        ammoMax = 15--max ammo
	},
	]]["ammo_338"] = {
	name = "Box of .338 Lapua",
	desc = "",
	price = 9250,--160,--90,
	model = "models/items/ammo/ammo_308.mdl",
	width = 2,
	height = 1,
	flag = "5",
	weight = 0.44,
	ammoBox = true,
	ammoType = "sky338",
	ammoMax = 10,
},
["ammo_338_ap"] = {
	name = "Box of AP .338 Lapua",
	desc = "",
	price = 10850,--180,--90,
	model = "models/items/ammo/ammo_308.mdl",
	width = 2,
	height = 1,
	flag = "5",
	weight = 0.47,
	ammoBox = true,
	ammoType = "sky338",
	ammoMax = 10,
	specammo = "ap"
},
["ammo_338_hp"] = {
	name = "Box of HP .338 Lapua",
	desc = "",
	price = 10800,--180,--90,
	model = "models/items/ammo/ammo_308.mdl",
	width = 2,
	height = 1,
	flag = "5",
	weight = 0.46,
	ammoBox = true,
	ammoType = "sky338",
	ammoMax = 10,
	specammo = "hp"
},
["ammo_buckshot"] = {
	name = "Box of 12 Gauge Buckshot",
	desc = "",
	price = 1350,--60,--35,--25,
	model = "models/items/ammo/ammo_12g.mdl",
	width = 2,
	height = 1,
	weight = 1.125,
	flag = "1",
	ammoBox = true,
	ammoType = "buckshot",
	ammoMax = 25,
},
["ammo_slug"] = {
	name = "Box of 12 Gauge Slug",
	desc = "",
	price = 1150,--85,--45,--25,
	model = "models/items/ammo/ammo_12g.mdl",
	width = 1,
	height = 1,
	weight = 1.125,
	flag = "1",
	ammoBox = true,
	ammoType = "buckshot",
	ammoMax = 25,
	specammo = "slug"
},
["ammo_frag"] = {
	name = "Box of 12 Gauge Frag",
	desc = "",
	price = 3200,-- 300,--125,--25,
	model = "models/items/ammo/ammo_12g.mdl",
	width = 1,
	height = 1,
	weight = 1.2,
	flag = "4",
	ammoBox = true,
	ammoType = "buckshot",
	ammoMax = 25,
	specammo = "frag"
},
["ammo_dragon"] = {
	name = "Box of 12 Gauge Dragon's Breath",
	desc = "",
	price = 3050,--320,--110,--25,
	model = "models/items/ammo/ammo_12g.mdl",
	width = 1,
	height = 1,
	weight = 1.175,
	flag = "3",
	ammoBox = true,
	ammoType = "buckshot",
	ammoMax = 25,
	specammo = "db"
},
["ammo_nslug"] = {
	name = "Box of 12 Gauge Non-Lethal Slug",
	desc = "",
	price = 1900,--280,--45,--25,
	model = "models/items/ammo/ammo_12g.mdl",
	width = 1,
	height = 1,
	weight = 1.15,
	flag = "3",
	ammoBox = true,
	ammoType = "buckshot",
	ammoMax = 25,
	specammo = "nslug"
},
--[[
["ammo_buckshot_large"] = {
	name = "Large Box of 12 Gauge",
	desc = "",
	price = 242,
	model = "models/Items/BoxMRounds.mdl",
	width = 2,
	height = 1,
	weight = 17.4,
	ammoBox = true,
	ammoType = "buckshot",
	ammoMax = 250,
},
]]
["ammo_23"] = {
	name = "Box of 23mm Shrapnel-25 Buckshot",
	desc = "",
	price = 4000,--60,--35,--25,
	model = "models/items/ammo/ammo_12g.mdl",
	width = 2,
	height = 1,
	weight = 0.5,
	flag = "5",
	ammoBox = true,
	ammoType = "sky23mm",
	ammoMax = 10,
},
["ammo_23slug"] = {
	name = "Box of 23mm Barricade",
	desc = "",
	price = 4350,--85,--45,--25,
	model = "models/items/ammo/ammo_12g.mdl",
	width = 2,
	height = 1,
	weight = 0.55,
	flag = "5",
	ammoBox = true,
	ammoType = "sky23mm",
	ammoMax = 10,
	specammo = "slug"
},
["ammo_762x54"] = {
	name = "Box of 7.62x54mmR",
	desc = "",
	price = 4200,--100,--60,--20,
	model = "models/stalker/ammo/762x54.mdl",
	width = 2,
	height = 1,
	weight = 0.44,
	flag = "1",
	ammoBox = true,
	ammoType = "sky762x54",
	ammoMax = 20,
},
["ammo_762x54_large"] = {
	name = "Large Box of 7.62x54mmR",
	desc = "",
	price = 42000,--650,--400,--180,
	model = "models/Items/BoxMRounds.mdl",
	width = 2,
	height = 2,
	weight = 4.5,
	baseWeight = 0.1,
	flag = "2",
    ammoBox = false,
	ammoType = "sky762x54",
	ammoMax = 200,
	dontfill = true, --misleading variable lmao this actually causes it to be filled
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["ammo_762x54_largee"] = {
	name = "Large Box of 7.62x54mmR",
	desc = "Default Empty",
	price = 150,--50,--400,--180,
	model = "models/Items/BoxMRounds.mdl",
	width = 2,
	height = 2,
	weight = 4.5,
	baseWeight = 0.1,
	flag = "2",
    ammoBox = false,
	ammoType = "sky762x51",
	ammoMax = 200,
--	dontfill = true, --misleading variable lmao this actually causes it to be filled
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["ammo_762x54_ap"] = {
	name = "Box of AP 7.62x54mmR",
	desc = "",
	price = 5400,--150,--80,--20,
	model = "models/stalker/ammo/762x54.mdl",
	width = 2,
	height = 1,
	weight = 0.45,
	flag = "2",
	ammoBox = true,
	ammoType = "sky762x54",
	ammoMax = 20,
	specammo = "ap"
},
["ammo_762x54_hp"] = {
	name = "Box of HP 7.62x54mmR",
	desc = "",
	price = 5050,--160,--60,--20,
	model = "models/stalker/ammo/762x54.mdl",
	width = 2,
	height = 1,
	weight = 0.45,
	flag = "2",
	ammoBox = true,
	ammoType = "sky762x54",
	ammoMax = 20,
	specammo = "hp"
},
["ammo_762x51"] = {
	name = "Box of 7.62x51mm NATO",
	desc = "",
	price = 3000,--60,--20,
	model = "models/stalker/ammo/762x51.mdl",
	width = 2,
	height = 1,
	weight = 0.44,
	flag = "2",
	ammoBox = true,
	ammoType = "sky762x51",
	ammoMax = 20,
},
["ammo_762x51_large"] = {
	name = "Large Box of 7.62x51mm NATO",
	desc = "",
	price = 30000,--400,--180,
	model = "models/Items/BoxMRounds.mdl",
	width = 2,
	height = 2,
	weight = 4.5,
	baseWeight = 0.1,
	flag = "3",
    ammoBox = false,
	ammoType = "sky762x51",
	ammoMax = 200,
	dontfill = true, --misleading variable lmao this actually causes it to be filled
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["ammo_762x51_largee"] = {
	name = "Large Box of 7.62x51mm NATO",
	desc = "Default Empty",
	price = 150,--400,--180,
	model = "models/Items/BoxMRounds.mdl",
	width = 2,
	height = 2,
	weight = 4.5,
	baseWeight = 0.1,
	flag = "3",
    ammoBox = false,
	ammoType = "sky762x51",
	ammoMax = 200,
--	dontfill = true, --misleading variable lmao this actually causes it to be filled
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["ammo_762x51_ap"] = {
	name = "Box of AP 7.62x51mm NATO",
	desc = "",
	price = 5000,--80,--20,
	model = "models/stalker/ammo/762x51.mdl",
	width = 2,
	height = 1,
	weight = 0.44,
	flag = "4",
	ammoBox = true,
	ammoType = "sky762x51",
	ammoMax = 20,
	specammo = "ap"
},
["ammo_762x51_hp"] = {
	name = "Box of HP 7.62x51mm NATO",
	desc = "",
	price = 4850,--60,--20,
	model = "models/stalker/ammo/762x51.mdl",
	width = 2,
	height = 1,
	weight = 0.44,
	flag = "4",
	ammoBox = true,
	ammoType = "sky762x51",
	ammoMax = 20,
	specammo = "hp"
},
["ammo_9x19"] = {
	name = "Box of 9x19mm",
	desc = "",
	price = 750,--60,--20,--9,
	model = "models/items/ammo/ammo_9mm.mdl",
	width = 1,
	height = 1,
	weight = 0.6,
	flag = "1",
	ammoBox = true,
	ammoType = "sky9x19",
	ammoMax = 50,
},
["ammo_9x19_large"] = {
	name = "Large Box of 9x19mm",
	desc = "",
	price = 7500,--280,--130,
	model = "models/Items/BoxMRounds.mdl",
	width = 2,
	height = 1,
	weight = 6.1,
	baseWeight = 0.1,
	flag = "1",
    ammoBox = false,
	ammoType = "sky9x19",
	ammoMax = 500,
	dontfill = true,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["ammo_9x19_largee"] = {
	name = "Large Box of 9x19mm",
	desc = "Default Empty",
	price = 150,--20,--130,
	model = "models/Items/BoxMRounds.mdl",
	width = 2,
	height = 1,
	weight = 6.1,
	baseWeight = 0.1,
	flag = "1",
    ammoBox = false,
	ammoType = "sky9x19",
	ammoMax = 500,
--	dontfill = true,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["ammo_9x19_hp"] = {
	name = "Box of HP 9x19mm",
	desc = "",
	price = 1450,--90,--40,--9,
	model = "models/items/ammo/ammo_9mm.mdl",
	width = 1,
	height = 1,
	weight = 0.56,
	flag = "5",
	ammoBox = true,
	ammoType = "sky9x19",
	ammoMax = 50,
	specammo = "hp"
},
["ammo_9x19_ap"] = {
	name = "Box of AP 9x19mm",
	desc = "",
	price = 1530,--80,--40,--9,
	model = "models/items/ammo/ammo_9mm.mdl",
	width = 1,
	height = 1,
	weight = 0.5,
	flag = "5",
	ammoBox = true,
	ammoType = "sky9x19",
	ammoMax = 50,
	specammo = "ap"
},
["ammo_9x18"] = {
	name = "Box of 9x18mm",
	desc = "",
	price = 750,--20,--9,
	model = "models/stalker/ammo/9x18.mdl",
	width = 1,
	height = 1,
	weight = 0.5,
	flag = "1",
	ammoBox = true,
	ammoType = "sky9x18",
	ammoMax = 50,
},
["ammo_9x18_large"] = {
	name = "Large Box of 9x18mm",
	desc = "",
	price = 7500,--130,
	model = "models/Items/BoxMRounds.mdl",
	width = 2,
	height = 1,
	weight = 5.1,
	baseWeight = 0.1,
	flag = "1",
    ammoBox = false,
	ammoType = "sky9x18",
	ammoMax = 500,
	dontfill = true,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["ammo_9x18_largee"] = {
	name = "Large Box of 9x18mm",
	desc = "Default Empty",
	price = 150,--130,
	model = "models/Items/BoxMRounds.mdl",
	width = 2,
	height = 1,
	weight = 5.1,
	baseWeight = 0.1,
	flag = "1",
    ammoBox = false,
	ammoType = "sky9x18",
	ammoMax = 500,
--	dontfill = true,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["ammo_9x18_hp"] = {
	name = "Box of HP 9x18mm",
	desc = "",
	price = 1420,--40,--9,
	model = "models/stalker/ammo/9x18.mdl",
	width = 1,
	height = 1,
	weight = 0.5,
	flag = "2",
	ammoBox = true,
	ammoType = "sky9x18",
	ammoMax = 50,
	specammo = "hp"
},
["ammo_9x18_ap"] = {
	name = "Box of AP 9x18mm",
	desc = "",
	price = 1525,--40,--9,
	model = "models/stalker/ammo/9x18.mdl",
	width = 1,
	height = 1,
	weight = 0.53,
	flag = "2",
	ammoBox = true,
	ammoType = "sky9x18",
	ammoMax = 50,
	specammo = "ap"
},
["ammo_9x39"] = {
	name = "Box of 9x39mm",
	desc = "",
	price = 2500,--20,--9,
	model = "models/stalker/ammo/9x39.mdl",
	width = 2,
	height = 1,
	weight = 0.49,
	flag = "3",
	ammoBox = true,
	ammoType = "sky9x39",
	ammoMax = 20,
},
["ammo_9x39_large"] = {
	name = "Large Box of 9x39mm",
	desc = "",
	price = 25000,--130,
	model = "models/Items/BoxMRounds.mdl",
	width = 2,
	height = 2,
	weight = 5,
	baseWeight = 0.1,
	flag = "3",
    ammoBox = false,
	ammoType = "sky9x39",
	ammoMax = 500,
	dontfill = true,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["ammo_9x39_largee"] = {
	name = "Large Box of 9x39mm",
	desc = "Default Empty",
	price = 150,--130,
	model = "models/Items/BoxMRounds.mdl",
	width = 2,
	height = 2,
	weight = 5,
	baseWeight = 0.1,
	flag = "3",
    ammoBox = false,
	ammoType = "sky9x39",
	ammoMax = 500,
--	dontfill = true,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["ammo_9x39_hp"] = {
	name = "Box of HP 9x39mm",
	desc = "",
	price = 3900,--40,--9,
	model = "models/stalker/ammo/9x39.mdl",
	width = 2,
	height = 1,
	weight = 0.48,
	flag = "4",
	ammoBox = true,
	ammoType = "sky9x39",
	ammoMax = 20,
	specammo = "hp"
},
["ammo_9x39_ap"] = {
	name = "Box of AP 9x39mm",
	desc = "",
	price = 4200,--40,--9,
	model = "models/stalker/ammo/9x39.mdl",
	width = 2,
	height = 1,
	weight = 0.48,
	flag = "4",
	ammoBox = true,
	ammoType = "sky9x39",
	ammoMax = 20,
	specammo = "ap"
},
["ammo_45acp"] = {
	name = "Box of .45 ACP",
	desc = "",
	price = 850,--60,--25,--15,
	model = "models/items/ammo/ammo_45acp.mdl",
	width = 1,
	height = 1,
	weight = 1.03,
	flag = "1",
	ammoBox = true,
	ammoType = "sky45acp",
	ammoMax = 50,
},
["ammo_45acp_hp"] = {
	name = "Box of HP .45 ACP",
	desc = "",
	price = 1500,--85,--45,--15,
	model = "models/items/ammo/ammo_45acp.mdl",
	width = 1,
	height = 1,
	weight = 1.05,
	flag = "5",
	ammoBox = true,
	ammoType = "sky45acp",
	ammoMax = 50,
	specammo = "hp"
},
["ammo_45acp_ap"] = {
	name = "Box of AP .45 ACP",
	desc = "",
	price = 1620,--75,--45,--15,
	model = "models/items/ammo/ammo_45acp.mdl",
	width = 1,
	height = 1,
	weight = 1.03,
	flag = "5",
	ammoBox = true,
	ammoType = "sky45acp",
	ammoMax = 50,
	specammo = "ap"
},
["ammo_45acp_large"] = {
	name = "Large Box of .45 ACP",
	desc = "",
	price = 8500,--300,--175,--124,
	model = "models/Items/BoxMRounds.mdl",
	width = 2,
	height = 1,
	weight = 10.4,
	baseWeight = 0.1,
	flag = "1",
    ammoBox = false,
	ammoType = "sky45acp",
	ammoMax = 500,
	dontfill = true,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["ammo_45acp_largee"] = {
	name = "Large Box of .45 ACP",
	desc = "Default Empty",
	price = 150,--30,--175,--124,
	model = "models/Items/BoxMRounds.mdl",
	width = 2,
	height = 1,
	weight = 10.4,
	baseWeight = 0.1,
	flag = "1",
    ammoBox = false,
	ammoType = "sky45acp",
	ammoMax = 500,
--	dontfill = true,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["ammo_50ae"] = {
	name = "Box of .50 AE",
	desc = "",
	price = 2100,--35,--30,
	model = "models/stalker/ammo/magnum.mdl",
	width = 1,
	height = 1,
	weight = 0.4,
	flag = "3",
	ammoBox = true,
	ammoType = "sky50ae",
	ammoMax = 20,
},
["ammo_50ae_ap"] = {
	name = "Box of AP .50 AE",
	desc = "",
	price = 3100,--65,--30,
	model = "models/stalker/ammo/magnum.mdl",
	width = 1,
	height = 1,
	weight = 0.41,
	flag = "4",
	ammoBox = true,
	ammoType = "sky50ae",
	ammoMax = 20,
	specammo = "ap"
},
["ammo_50ae_hp"] = {
	name = "Box of HP .50 AE",
	desc = "",
	price = 2950,--65,--30,
	model = "models/stalker/ammo/magnum.mdl",
	width = 1,
	height = 1,
	weight = 0.4,
	flag = "4",
	ammoBox = true,
	ammoType = "sky50ae",
	ammoMax = 20,
	specammo = "hp"
},
--[[
["ammo_762x25"] = {
	name = "Box of 7.62x25mm",
	desc = "",
	price = 27,
	model = "models/stalker/ammo/9x18.mdl",
	width = 1,
	height = 1,
	weight = 0.67,
	ammoBox = true,
	ammoType = "sky762x25",
	ammoMax = 50,
},
]]
["ammo_762x39"] = {
	name = "Box of 7.62x39mm",
	desc = "",
	price = 2100,--60,--20,--5,
	model = "models/stalker/ammo/762x39.mdl",
	width = 2,
	height = 1,
	weight = 0.32,
	flag = "1",
	ammoBox = true,
	ammoType = "sky762x39",
	ammoMax = 20,
},
["ammo_762x39_ap"] = {
	name = "Box of AP 7.62x39mm",
	desc = "",
	price = 3030,--80,--40,--5,
	model = "models/stalker/ammo/762x39.mdl",
	width = 2,
	height = 1,
	weight = 0.32,
	flag = "2",
	ammoBox = true,
	ammoType = "sky762x39",
	ammoMax = 20,
	specammo = "ap"
},
["ammo_762x39_hp"] = {
	name = "Box of HP 7.62x39mm",
	desc = "",
	price = 2840,--90,--40,--5,
	model = "models/stalker/ammo/762x39.mdl",
	width = 2,
	height = 1,
	weight = 0.32,
	flag = "2",
	ammoBox = true,
	ammoType = "sky762x39",
	ammoMax = 20,
	specammo = "hp"
},
["ammo_762x39_large"] = {
	name = "Large Box of 7.62x39mm",
	desc = "",
	price = 21000,--560,--160,--177,
	model = "models/Items/BoxMRounds.mdl",
	width = 2,
	height = 2,
	weight = 3.3,
	baseWeight = 0.1,
	flag = "2",
    ammoBox = false,
	ammoType = "sky762x39",
	ammoMax = 200,
	dontfill = true,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["ammo_762x39_largee"] = {
	name = "Large Box of 7.62x39mm",
	desc = "Default Empty",
	price = 150,--60,--160,--177,
	model = "models/Items/BoxMRounds.mdl",
	width = 2,
	height = 2,
	weight = 3.3,
	baseWeight = 0.1,
	flag = "2",
    ammoBox = false,
	ammoType = "sky762x39",
	ammoMax = 200,
--	dontfill = true,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["ammo_556"] = {
	name = "Box of 5.56x45mm",
	desc = "",
	price = 2000,--60,--19,--5,
	model = "models/stalker/ammo/556x45.mdl",
	width = 2,
	height = 1,
	weight = 0.23,
	flag = "2",
	ammoBox = true,
	ammoType = "sky556",
	ammoMax = 20,
},
["ammo_556_ap"] = {
	name = "Box of AP 5.56x45mm",
	desc = "",
	price = 2700,--80,--39,--5,
	model = "models/stalker/ammo/556x45.mdl",
	width = 2,
	height = 1,
	weight = 0.24,
	flag = "3",
	ammoBox = true,
	ammoType = "sky556",
	ammoMax = 20,
	specammo = "ap"
},
["ammo_556_hp"] = {
	name = "Box of HP 5.56x45mm",
	desc = "",
	price = 2550,--90,--39,--5,
	model = "models/stalker/ammo/556x45.mdl",
	width = 1,
	height = 1,
	weight = 0.23,
	flag = "3",
	ammoBox = true,
	ammoType = "sky556",
	ammoMax = 20,
	specammo = "hp"
},
["ammo_556_large"] = {
	name = "Large Box of 5.56x45mm",
	desc = "",
	price = 20000,--550,--156,--180,
	model = "models/Items/BoxMRounds.mdl",
	width = 2,
	height = 2,
	weight = 2.4,
	baseWeight = 0.1,
	flag = "2",
	ammoBox = false,
	ammoType = "sky556",
	ammoMax = 200,
	dontfill = true,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["ammo_556_largee"] = {
	name = "Large Box of 5.56x45mm",
	desc = "Default Empty",
	price = 150,--50,--156,--180,
	model = "models/Items/BoxMRounds.mdl",
	width = 2,
	height = 2,
	weight = 2.4,
	baseWeight = 0.1,
	flag = "2",
	ammoBox = false,
	ammoType = "sky556",
	ammoMax = 200,
--	dontfill = true,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["ammo_545"] = {
	name = "Box of 5.45x39mm",
	desc = "",
	price = 1900,--60,--19,--5,
	model = "models/stalker/ammo/545x39.mdl",
	width = 2,
	height = 1,
	weight = 0.21,
	flag = "1",
	ammoBox = true,
	ammoType = "sky545",
	ammoMax = 20,
},
["ammo_545_ap"] = {
	name = "Box of AP 5.45x39mm",
	desc = "",
	price = 2500,--80,--39,--5,
	model = "models/stalker/ammo/545x39.mdl",
	width = 2,
	height = 1,
	weight = 0.21,
	flag = "2",
	ammoBox = true,
	ammoType = "sky545",
	ammoMax = 20,
	specammo = "ap"
},
["ammo_545_hp"] = {
	name = "Box of HP 5.45x39mm",
	desc = "",
	price = 2350,--90,--39,--5,
	model = "models/stalker/ammo/545x39.mdl",
	width = 2,
	height = 1,
	weight = 0.21,
	flag = "2",
	ammoBox = true,
	ammoType = "sky545",
	ammoMax = 20,
	specammo = "hp"
},
["ammo_545_large"] = {
	name = "Large Box of 5.45x39mm",
	desc = "",
	price = 19000,--580,--157,--190,
	model = "models/Items/BoxMRounds.mdl",
	width = 2,
	height = 2,
	weight = 2.2,
	baseWeight = 0.1,
	flag = "2",
	ammoBox = false,
	ammoType = "sky545",
	ammoMax = 200,
	dontfill = true,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["ammo_545_largee"] = {
	name = "Large Box of 5.45x39mm",
	desc = "Default Empty",
	price = 150,--50,--157,--190,
	model = "models/Items/BoxMRounds.mdl",
	width = 2,
	height = 1,
	weight = 2.2,
	baseWeight = 0.1,
	flag = "2",
	ammoBox = false,
	ammoType = "sky545",
	ammoMax = 200,
	--dontfill = true,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},

["mag_545ak"] = {
	name = "5.45x39mm AK Magazine",
	desc = "",
	price = 400,--24,--10,--7,
	model = "models/items/ammo/ak74.mdl",
	width = 1,
	height = 2,
	weight = 0.53,
	baseWeight = 0.215,
	flag = "1",
	ammoBox = false,
	ammoType = "sky545",
	ammoMax = 30,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_762ak"] = {
	name = "7.62x39mm AK Magazine",
	desc = "",
	price = 600,--29,--13,--10,
	model = "models/weapons/unloaded/rif_ak47_mag.mdl",
	width = 1,
	height = 2,
	weight = 0.65,
	baseWeight = 0.17,
	flag = "2",
	ammoBox = false,
	ammoType = "sky762x39",
	ammoMax = 30,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_stanag"] = {
	name = "STANAG Magazine",
	desc = "",
	price = 800,--22,--9,--6,
	model = "models/weapons/unloaded/rif_m4a1_mag.mdl",
	width = 1,
	height = 2,
	weight = 0.477,
	baseWeight = 0.117,
	flag = "2",
	ammoBox = false,
	ammoType = "sky556",
	ammoMax = 30,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_aug"] = {
	name = "AUG Magazine",
	desc = "",
	price = 720,--11,--10,
	model = "models/weapons/unloaded/rif_aug_mag.mdl",
	width = 1,
	height = 2,
	weight = 0.49,
	baseWeight = 0.130,
	flag = "3",
	ammoBox = false,
	ammoType = "sky556",
	ammoMax = 30,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_deserteagle"] = {
	name = "Desert Eagle Magazine",
	desc = "",
	price = 800,--24,--20,
	model = "models/weapons/unloaded/pist_deagle_mag.mdl",
	width = 1,
	height = 1,
	weight = 0.46,
	baseWeight = 0.32,
	flag = "3",
	ammoBox = false,
	ammoType = "sky50ae",
	ammoMax = 7,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_famas"] = {
	name = "FAMAS Magazine",
	desc = "",
	price = 750,--11,
	model = "models/weapons/unloaded/rif_famas_mag.mdl",
	width = 1,
	height = 2,
	weight = 0.44,
	baseWeight = 0.14,
	flag = "2",
	ammoBox = false,
	ammoType = "sky556",
	ammoMax = 25,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_g36"] = {
	name = "G36 Magazine",
	desc = "",
	price = 850,--25,--12,
	model = "models/weapons/unloaded/rif_sg552_mag.mdl",
	width = 1,
	height = 2,
	weight = 0.487,
	baseWeight = 0.127,
	flag = "3",
	ammoBox = false,
	ammoType = "sky556",
	ammoMax = 30,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_glock"] = {
	name = "Glock Magazine",
	desc = "",
	price = 400,--7,--5,
	model = "models/weapons/unloaded/pist_glock18_mag.mdl",
	width = 1,
	height = 1,
	weight = 0.266,
	baseWeight = 0.096,
	flag = "2",
	ammoBox = false,
	ammoType = "sky9x19",
	ammoMax = 17,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
--[[
["mag_cz"] = {
	name = "CZ 75 Magazine",
	desc = "",
	price = 12,--7,--5,
	model = "models/weapons/unloaded/pist_glock18_mag.mdl",
	width = 1,
	height = 1,
	weight = 0.47,
	baseWeight = 0.17,
	flag = "1",
	ammoBox = false,
	ammoType = "sky9x19",
	ammoMax = 16,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
]]
["mag_1911"] = {
	name = "M1911 Magazine",
	desc = "",
	price = 300,--8,--6,
	model = "models/weapons/unloaded/pist_p228_mag.mdl",
	width = 1,
	height = 1,
	weight = 0.204,
	baseWeight = 0.06,
	flag = "1",
	ammoBox = false,
	ammoType = "sky45acp",
	ammoMax = 7,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_m9"] = {
	name = "M9 Magazine",
	desc = "",
	price = 450,--8,--6,
	model = "models/weapons/unloaded/pist_fiveseven_mag.mdl",
	width = 1,
	height = 1,
	weight = 0.316,
	baseWeight = 0.136,
	flag = "1",
	ammoBox = false,
	ammoType = "sky9x19",
	ammoMax = 15,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_mp5"] = {
	name = "MP5 Magazine",
	desc = "",
	price = 600,--10,--8,
	model = "models/weapons/unloaded/smg_mp5_mag.mdl",
	width = 1,
	height = 2,
	weight = 0.53,
	baseWeight = 0.17,
	flag = "1",
	ammoBox = false,
	ammoType = "sky9x19",
	ammoMax = 30,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_minimi"] = {
	name = "Para Box",
	desc = "",
	price = 1250,--35,--25,
	model = "models/weapons/unloaded/mach_m249para_mag.mdl",
	width = 2,
	height = 2,
	weight = 1.7,
	baseWeight = 0.5,
	flag = "4",
	baseWeight = 1,
	ammoBox = false,
	ammoType = "sky556",
	ammoMax = 100,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_rpk"] = {
	name = "RPK Drum Magazine",
	desc = "",
	price = 1400,--30,--20,
	model = "models/items/ammo/drum.mdl",
	width = 2,
	height = 2,
	weight = 2.1,
	flag = "3",
	baseWeight = 0.9,
	ammoBox = false,
	ammoType = "sky762x39",
	ammoMax = 75,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_ump"] = {
	name = "UMP Magazine",
	desc = "",
	price = 580,--10,--8,
	model = "models/weapons/unloaded/fix/smg_ump45_mag.mdl",
	width = 1,
	height = 2,
	weight = 0.685,
	baseWeight = 0.17,
	flag = "2",
	ammoBox = false,
	ammoType = "sky45acp",
	ammoMax = 25,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_kriss"] = {
	name = "Vector Magazine",
	desc = "",
	price = 770,--10,--8,
	model = "models/weapons/unloaded/fix/smg_ump45_mag.mdl",
	width = 1,
	height = 2,
	weight = 0.65,
	baseWeight = 0.14,
	flag = "3",
	ammoBox = false,
	ammoType = "sky45acp",
	ammoMax = 25,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_usp"] = {
	name = "USP Magazine",
	desc = "",
	price = 340,--9,--7,
	model = "models/weapons/unloaded/pist_usp_mag.mdl",
	width = 1,
	height = 1,
	weight = 0.345,
	baseWeight = 0.098,
	flag = "1",
	ammoBox = false,
	ammoType = "sky45acp",
	ammoMax = 12,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_usp9"] = {
	name = "USP Magazine (9mm)",
	desc = "",
	price = 330,--9,--7,
	model = "models/weapons/unloaded/pist_usp_mag.mdl",
	width = 1,
	height = 1,
	weight = 0.269,
	baseWeight = 0.063,
	flag = "1",
	ammoBox = false,
	ammoType = "sky9x19",
	ammoMax = 18,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_9mm32"] = {
	name = "9x19mm Stick Magazine",
	desc = "",
	price = 890,--9,--7,
	model = "models/weapons/unloaded/smg_mac10_mag.mdl",
	width = 1,
	height = 2,
	weight = 0.594,
	baseWeight = 0.21,
	flag = "3",
	ammoBox = false,
	ammoType = "sky9x19",
	ammoMax = 32,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
--[[
["mag_rfb"] = {
	name = "RFB Magazine",
	desc = "",
	price = 70,--40,--30,
	model = "models/weapons/unloaded/snip_scout_mag.mdl",
	width = 1,
	height = 1,
	flag = "2",
	ammoBox = false,
	ammoType = "sky762x51",
	ammoMax = 20,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},]]
["mag_evo"] = {
	name = "Scorpion Evo 3 Magazine",
	desc = "",
	price = 860,--10,--8,
	model = "models/weapons/unloaded/fix/smg_ump45_mag.mdl",
	width = 1,
	height = 2,
	weight = 0.52,
	baseWeight = 0.3,
	flag = "2",
	ammoBox = false,
	ammoType = "sky9x19",
	ammoMax = 30,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},--[[
["mag_spectre"] = {
	name = "Spectre M4 Magazine",
	desc = "",
	price = 15,--8,--7,
	model = "models/weapons/unloaded/smg_mac10_mag.mdl",
	width = 1,
	height = 1,
	flag = "1",
	ammoBox = false,
	ammoType = "sky9x19",
	ammoMax = 30,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_px4"] = {
	name = "PX4 Magazine",
	desc = "",
	price = 13,--8,--13,
	model = "models/weapons/unloaded/pist_fiveseven_mag.mdl",
	width = 1,
	height = 1,
	flag = "1",
	ammoBox = false,
	ammoType = "sky9x19",
	ammoMax = 15,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_scarh"] = {
	name = "SCAR-H Magazine",
	desc = "",
	price = 26,--12,
	model = "models/weapons/unloaded/fix/snip_g3sg1_mag.mdl",
	width = 1,
	height = 1,
	weight = 1.33,
	baseWeight = 0.75,
	flag = "3",
	ammoBox = false,
	ammoType = "sky762x51",
	ammoMax = 20,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},]]
["mag_val"] = {
	name = "AS Val Magazine",
	desc = "",
	price = 1000,--12,
	model = "models/items/ammo/vss.mdl",
	width = 1,
	height = 2,
	weight = 0.79,
	baseWeight = 0.3,
	flag = "3",
	ammoBox = false,
	ammoType = "sky9x39",
	ammoMax = 20,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},--[[
["mag_fal"] = {
	name = "FN Fal Magazine",
	desc = "",
	price = 27,--12,
	model = "models/items/ammo/fal.mdl",
	width = 1,
	height = 1,
	weight = 1.33,
	baseWeight = 0.75,
	flag = "2",
	ammoBox = false,
	ammoType = "sky762x51",
	ammoMax = 20,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_galil"] = {
	name = "Galil Magazine",
	desc = "",
	price = 23,--12,
	model = "models/weapons/unloaded/rif_galil_mag.mdl",
	width = 1,
	height = 1,
	weight = 1.33,
	baseWeight = 0.75,
	flag = "2",
	ammoBox = false,
	ammoType = "sky556",
	ammoMax = 35,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},]]
["mag_mp443"] = {
	name = "MP443 Magazine",
	desc = "",
	price = 350,--12,
	model = "models/weapons/unloaded/pist_glock18_mag.mdl",
	width = 1,
	height = 1,
	weight = 0.321,
	baseWeight = 0.105,
	flag = "1",
	ammoBox = false,
	ammoType = "sky9x19",
	ammoMax = 18,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_pkp"] = {
	name = "PKP Box",
	desc = "",
	price = 1550,--12,
	model = "models/stalker/ammo/pkm.mdl",
	width = 2,
	height = 2,
	weight = 2.6,
	baseWeight = 0.4,
	flag = "4",
	ammoBox = false,
	ammoType = "sky762x54",
	ammoMax = 100,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_pm"] = {
	name = "Makarov Magazine",
	desc = "",
	price = 190,--12,
	model = "models/weapons/unloaded/pist_p228_mag.mdl",
	width = 1,
	height = 1,
	weight = 0.124,
	baseWeight = 0.044,
	flag = "1",
	ammoBox = false,
	ammoType = "sky9x18",
	ammoMax = 8,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
--[[
["mag_svd"] = {
	name = "SVD Magazine",
	desc = "",
	price = 20,--12,
	model = "models/weapons/unloaded/pist_p228_mag.mdl", --need model didnt do
	width = 1,
	height = 1,
	weight = 1.33,
	baseWeight = 0.75,
	flag = "2",
	ammoBox = false,
	ammoType = "sky762x54",
	ammoMax = 10,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_uzi"] = {
	name = "UZI Magazine",
	desc = "",
	price = 2,--12,
	model = "models/weapons/unloaded/smg_mac10_mag.mdl",
	width = 1,
	height = 1,
	weight = 1.33,
	baseWeight = 0.75,
	flag = "1",
	ammoBox = false,
	ammoType = "sky9x19",
	ammoMax = 32,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
]]

["mag_p226"] = {
	name = "P226 Magazine",
	desc = "",
	price = 340,--12,
	model = "models/weapons/unloaded/pist_p228_mag.mdl",
	width = 1,
	height = 1,
	weight = 0.276,
	baseWeight = 0.096,
	flag = "1",
	ammoBox = false,
	ammoType = "sky9x19",
	ammoMax = 15,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_g3"] = {
	name = "G3 Magazine",
	desc = "",
	price = 930,--12,
	model = "models/weapons/unloaded/fix/snip_g3sg1_mag.mdl",
	width = 1,
	height = 2,
	weight = 0.708,
	baseWeight = 0.268,
	flag = "3",
	ammoBox = false,
	ammoType = "sky762x51",
	ammoMax = 20,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_sg55x"] = {
	name = "SG55x Magazine",
	desc = "",
	price = 840,--12,
	model = "models/weapons/unloaded/rif_sg552_mag.mdl",
	width = 1,
	height = 2,
	weight = 0.47,
	baseWeight = 0.11,
	flag = "3",
	ammoBox = false,
	ammoType = "sky556",
	ammoMax = 30,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_sksclip"] = {
	name = "SKS Clip",
	desc = "",
	price = 190,--12,
	model = "models/gibs/metal_gib1.mdl",
	width = 1,
	height = 1,
	weight = 0.17,
	baseWeight = 0.01,
	flag = "1",
	ammoBox = false,
	ammoType = "sky762x39",
	ammoMax = 10,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_sks20"] = {
	name = "SKS 20rd Detachable Magazine",
	desc = "",
	price = 500,--12,
	model = "models/weapons/unloaded/rif_ak47_mag.mdl",
	width = 1,
	height = 2,
	weight = 0.44,
	baseWeight = 0.112,
	flag = "2",
	ammoBox = false,
	ammoType = "sky762x39",
	ammoMax = 20,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
["mag_svd"] = {
	name = "SVD Magazine",
	desc = "",
	price = 650,--12,
	model = "models/weapons/unloaded/rif_sg552_mag.mdl",
	width = 1,
	height = 1,
	weight = 0.332,
	baseWeight = 0.112,
	flag = "4",
	ammoBox = false,
	ammoType = "sky762x54",
	ammoMax = 10,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},
--[[
["mag_ar2"] = {
	name = "AR2 Mag",
	desc = "",
	price = 5,--12,
	model = "models/weapons/tfa_mmod/w_irifle_magazine.mdl",
	width = 1,
	height = 1,
	weight = 1.33,
	baseWeight = 0.75,
	flag = "1",
	ammoBox = false,
	ammoType = "ar2",
	ammoMax = 30,
	dontfill = true, --this is actually the other way around woops
},
["ammo_ar2"] = {
	name = "Dark Energy Cartridges",
	desc = "",
	price = 25,--12,
	model = "models/Items/BoxMRounds.mdl",
	width = 1,
	height = 1,
	weight = 1.33,
	baseWeight = 0.75,
	flag = "1",
	ammoBox = true,
	ammoType = "ar2",
	ammoMax = 150,
},
]]
--modular weps mags
--[[
["mag_akx"] = {
	name = "AKX Magazine",
	desc = RarityText(RARITY_UNCOMMON).."",
	price = 12,--12,
	model = "models/sky/mags/akx_mag.mdl",
	width = 1,
	height = 1,
	weight = 1.33,
	baseWeight = 0.75,
	flag = "2",
	ammoBox = false,
	ammoType = "sky545",
	ammoMax = 30,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"},
	iconCam = {	
		pos = Vector(-10.647581100464, -0.30974146723747, -3.5594799518585),
		ang = Angle(0, 0, 0),
		entAng = Angle(0, -90, 0),
		fov = 45,
		outline = true,
		outlineColor = RARITY_COLORS[RARITY_UNCOMMON],
	}
},
["mag_akx_drum"] = {
	name = "AKX Drum Magazine",
	desc = RarityText(RARITY_RARE).."",
	price = 12,--12,
	model = "models/sky/mags/akx_mag_drum.mdl",
	width = 1,
	height = 2,
	weight = 1.33,
	baseWeight = 0.75,
	flag = "2",
	ammoBox = false,
	ammoType = "sky545",
	ammoMax = 60,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"},
	iconCam = {		
		pos = Vector(-10.647581100464, -0.30974146723747, -3.5594799518585),
		ang = Angle(0, 0, 0),
		entAng = Angle(0, -90, 0),
		fov = 29.484707082675,
		outline = true,
		outlineColor = RARITY_COLORS[RARITY_RARE],
	}
},
["mag_akx_snip"] = {
	name = "AKX Sniper Magazine",
	desc = RarityText(RARITY_RARE).."",
	price = 12,--12,
	model = "models/sky/mags/akx_mag_snip.mdl",
	width = 1,
	height = 1,
	weight = 1.33,
	baseWeight = 0.75,
	flag = "2",
	ammoBox = false,
	ammoType = "sky762x39",
	ammoMax = 20,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"},
	iconCam = {	
		pos = Vector(-10.647581100464, -0.30974146723747, -3.5594799518585),
		ang = Angle(0, 0, 0),
		entAng = Angle(0, -90, 0),
		fov = 45,
		outline = true,
		outlineColor = RARITY_COLORS[RARITY_RARE],
	}
},
["mag_hkx"] = {
	name = "HKX Magazine",
	desc = RarityText(RARITY_UNCOMMON).."",
	price = 12,--12,
	model = "models/sky/mags/hkx_mag.mdl",
	width = 1,
	height = 1,
	weight = 1.33,
	baseWeight = 0.75,
	flag = "2",
	ammoBox = false,
	ammoType = "sky556",
	ammoMax = 30,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"},
	iconCam = {	
		pos = Vector(-10.647581100464, -0.30974146723747, -3.5594799518585),
		ang = Angle(0, 0, 0),
		entAng = Angle(0, -90, 0),
		fov = 45,
		outline = true,
		outlineColor = RARITY_COLORS[RARITY_UNCOMMON],
	}
},
["mag_hkx_drum"] = {
	name = "HKX Drum Magazine",
	desc = RarityText(RARITY_RARE).."",
	price = 12,--12,
	model = "models/sky/mags/hkx_mag_drum.mdl",
	width = 1,
	height = 2,
	weight = 1.33,
	baseWeight = 0.75,
	flag = "2",
	ammoBox = false,
	ammoType = "sky556",
	ammoMax = 60,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"},
	iconCam = {	
		pos = Vector(-9.3552532196045, 1.1615278720856, -3.6548936367035),
		ang = Angle(0, 0, 0),
		entAng = Angle(0, -90, 0),
		fov = 29.424621192776,
		outline = true,
		outlineColor = RARITY_COLORS[RARITY_RARE],
	}
},
["mag_hkx_snip"] = {
	name = "HKX Sniper Magazine",
	desc = RarityText(RARITY_RARE).."",
	price = 12,--12,
	model = "models/sky/mags/hkx_mag_snip.mdl",
	width = 1,
	height = 1,
	weight = 1.33,
	baseWeight = 0.75,
	flag = "2",
	ammoBox = false,
	ammoType = "sky762x51",
	ammoMax = 20,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"},
	iconCam = {	
		pos = Vector(-9.3552532196045, 1.4111469984055, -3.8958749771118),
		ang = Angle(0, 0, 0),
		entAng = Angle(0, -90, 0),
		fov = 36.560920967613,
		outline = true,
		outlineColor = RARITY_COLORS[RARITY_RARE],
	}
},
["mag_mac"] = {
	name = "MACX 9x19mm Magazine",
	desc = RarityText(RARITY_UNCOMMON).."",
	price = 12,--12,
	model = "models/sky/mags/mac_mag.mdl",
	width = 1,
	height = 1,
	weight = 1.33,
	baseWeight = 0.75,
	flag = "2",
	ammoBox = false,
	ammoType = "sky9x19",
	ammoMax = 32,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"},
	iconCam = {	
		pos = Vector(-12.376843452454, 6.3321108818054, -3.8958749771118),
		ang = Angle(0, 0, 0),
		entAng = Angle(0, -90, 0),
		fov = 36.560920967613,
		outline = true,
		outlineColor = RARITY_COLORS[RARITY_UNCOMMON],
	}
},
["mag_mac45"] = {
	name = "MACX .45 ACP Magazine",
	desc = RarityText(RARITY_RARE).."",
	price = 12,--12,
	model = "models/sky/mags/mac_mag.mdl",
	width = 1,
	height = 1,
	weight = 1.33,
	baseWeight = 0.75,
	flag = "2",
	ammoBox = false,
	ammoType = "sky45acp",
	ammoMax = 25,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"},
	iconCam = {	
		pos = Vector(-12.376843452454, 6.3321108818054, -3.8958749771118),
		ang = Angle(0, 0, 0),
		entAng = Angle(0, -90, 0),
		fov = 36.560920967613,
		outline = true,
		outlineColor = RARITY_COLORS[RARITY_RARE],
	}
},
["mag_pistolx"] = {
	name = "HS2100 Magazine",
	desc = RarityText(RARITY_COMMON).."",
	price = 12,--12,
	model = "models/sky/mags/pistol_mag.mdl",
	width = 1,
	height = 1,
	weight = 1.33,
	baseWeight = 0.75,
	flag = "1",
	ammoBox = false,
	ammoType = "sky9x19",
	ammoMax = 16,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"},
	iconCam = {	
		pos = Vector(-11.314499855042, 2.565750837326, -3.1306736469269),
		ang = Angle(0, 0, 0),
		entAng = Angle(0, -90, 0),
		fov = 36.817431980752,
		outline = true,
		outlineColor = RARITY_COLORS[RARITY_COMMON],
	}
},
["mag_pistolx_ext"] = {
	name = "HS2100 Extended Magazine",
	desc = RarityText(RARITY_UNCOMMON).."",
	price = 12,--12,
	model = "models/sky/mags/pistol_mag_ext.mdl",
	width = 1,
	height = 1,
	weight = 1.33,
	baseWeight = 0.75,
	flag = "1",
	ammoBox = false,
	ammoType = "sky9x19",
	ammoMax = 16,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"},
	iconCam = {	
		pos = Vector(-13.686552047729, 2.565750837326, -4.5243635177612),
		ang = Angle(0, 0, 0),
		entAng = Angle(0, -90, 0),
		fov = 42.125263040685,
		outline = true,
		outlineColor = RARITY_COLORS[RARITY_UNCOMMON],
	}
},
]]
--[[
["mag_wa2000"] = {
	name = "WA-2000 Magazine",
	desc = "",
	price = 50,--13,--12,
	model = "models/weapons/unloaded/snip_awp_mag.mdl",
	width = 1,
	height = 1,
	flag = "2",
	ammoBox = false,
	ammoType = "sky762x51",
	ammoMax = 6,
	otherMagTypes = {["default"] = "Normal", ["hp"] = "Hollow Point", ["ap"] = "Armor Piercing"}
},]]
}

--list of atts
PLUGIN.attList = {
	--[[
	["id"] = {
        name = "name",
        desc = "desc",
        price = 0,
        model = "model",
        width = 1,
        height = 1,
        cat = 1,
        attID = "attid"
	},
	]]
	--[["sky_smartlink"] = {
        name = "SmartLink Receiver",
        desc = "Required to be attached to a weapon to use the SmartLink cyberware on it.",
        price = 14000,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
        weight = 3.3,
		flag = "4",
        cat = 2,
        attID = "sky_smartlink",
    },]]
	["ins2_fg_gp25_sky"] = {
        name = "GP-25",
        desc = "A grenade launcher. Only compatible with certain weapons.",
        price = 16500,
        model = "models/Items/BoxMRounds.mdl",
        width = 2,
        height = 1,
        weight = 1.3,
		flag = "s",
        cat = 8,
        attID = "ins2_fg_gp25_sky",
    },
    ["ins2_fg_m203_sky"] = {
        name = "M203",
        desc = "A grenade launcher. Only compatible with certain weapons.",
        price = 15200,
        model = "models/Items/BoxMRounds.mdl",
        width = 2,
        height = 1,
        weight = 1.36,
		flag = "s",
        cat = 8,
        attID = "ins2_fg_m203_sky",
    },
    ["ins2_ub_light"] = {
        name = "Flashlight Attachment",
        desc = "A flashlight rail attachment.",
        price = 2250,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
		flag = "j",
        weight = 0.2,
        cat = 9,
        attID = "ins2_ub_light",
		destroyval = {
			["flashlight"] = 1,
			["comp_wire1"] = 1,
		}
    },
    ["ins2_ub_laser"] = {
        name = "Laser Attachment",
        desc = "A laser sight attachment.",
        price = 2800,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
        weight = 0.05,
		flag = "k",
        cat = 9,
        attID = "ins2_ub_laser",
    },
    ["ins2_br_supp_45"] = {
        name = ".45 ACP Suppressor",
        desc = "A suppressor for .45 ACP weapons.",
        price = 5800,--200,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
        weight = 0.54,
		flag = "j",
        cat = 1,
		attID = "ins2_br_supp_45",
		expand = {
			--width = x, add right == 1, 0; add left == 1, -1;
			--			remove right == -1, 0; remove left == -1, 1
			--height = y, same as above but instead of left its down, and right is up
			wh = "w",
			sizemod = 1,
			posmod = -1,
			--used for removing
			sizemodd = -1,
			posmodd = 1,
		},
    },
    ["ins2_br_supp_9mm"] = {
        name = "9x19mm Suppressor",
        desc = "A suppressor for 9x19mm weapons.",
        price = 5480,--200,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
        weight = 0.2,
		flag = "j",
        cat = 1,
        attID = "ins2_br_supp_9mm",
		expand = {
			--width = x, add right == 1, 0; add left == 1, -1;
			--			remove right == -1, 0; remove left == -1, 1
			--height = y, same as above but instead of left its down, and right is up
			wh = "w",
			sizemod = 1,
			posmod = -1,
			--used for removing
			sizemodd = -1,
			posmodd = 1,
		},
    },
    ["ins2_br_supp_545"] = {
        name = "5.45x39mm Suppressor",
        desc = "A suppressor for 5.45x39mm weapons.",
        price = 10300,--500,
        model = "models/Items/BoxMRounds.mdl",
        width = 2,
        height = 1,
        weight = 0.58,
		flag = "l",
        cat = 1,
        attID = "ins2_br_supp_545",
		expand = {
			--width = x, add right == 1, 0; add left == 1, -1;
			--			remove right == -1, 0; remove left == -1, 1
			--height = y, same as above but instead of left its down, and right is up
			wh = "w",
			sizemod = 1,
			posmod = -1,
			--used for removing
			sizemodd = -1,
			posmodd = 1,
		},
    },
    ["ins2_br_supp_556"] = {
        name = "5.56x45mm Suppressor",
        desc = "A suppressor for 5.56x45mm weapons.",
        price = 10600,--500,
        model = "models/Items/BoxMRounds.mdl",
        width = 2,
        height = 1,
        weight = 1,
		flag = "l",
        cat = 1,
        attID = "ins2_br_supp_556",
		expand = {
			--width = x, add right == 1, 0; add left == 1, -1;
			--			remove right == -1, 0; remove left == -1, 1
			--height = y, same as above but instead of left its down, and right is up
			wh = "w",
			sizemod = 1,
			posmod = -1,
			--used for removing
			sizemodd = -1,
			posmodd = 1,
		},
    },
    ["ins2_br_supp_762x39"] = {
        name = "7.62x39mm Suppressor",
        desc = "A suppressor for 7.62x39mm weapons.",
        price = 11600,--500,
        model = "models/Items/BoxMRounds.mdl",
        width = 2,
        height = 1,
		flag = "l",
        weight = 0.55,
        cat = 1,
        attID = "ins2_br_supp_762x39",
		expand = {
			--width = x, add right == 1, 0; add left == 1, -1;
			--			remove right == -1, 0; remove left == -1, 1
			--height = y, same as above but instead of left its down, and right is up
			wh = "w",
			sizemod = 1,
			posmod = -1,
			--used for removing
			sizemodd = -1,
			posmodd = 1,
		},
	},
    ["ins2_br_supp_762x51"] = {
        name = "7.62x51mm NATO Suppressor",
        desc = "A suppressor for 7.62x51mm weapons.",
        price = 11150,--500,
        model = "models/Items/BoxMRounds.mdl",
        width = 2,
        height = 1,
		flag = "l",
        weight = 0.56,
        cat = 1,
        attID = "ins2_br_supp_762x51",
		expand = {
			--width = x, add right == 1, 0; add left == 1, -1;
			--			remove right == -1, 0; remove left == -1, 1
			--height = y, same as above but instead of left its down, and right is up
			wh = "w",
			sizemod = 1,
			posmod = -1,
			--used for removing
			sizemodd = -1,
			posmodd = 1,
		},
	},
    ["ins2_br_supp_762x54"] = {
        name = "7.62x54mmR Suppressor",
        desc = "",
        price = 14500,
        model = "models/Items/BoxMRounds.mdl",
        width = 2,
        height = 1,
		weight = 0.7,
		flag = "l",
        cat = 1,
        attID = "ins2_br_supp_762x54",
		expand = {
			--width = x, add right == 1, 0; add left == 1, -1;
			--			remove right == -1, 0; remove left == -1, 1
			--height = y, same as above but instead of left its down, and right is up
			wh = "w",
			sizemod = 1,
			posmod = -1,
			--used for removing
			sizemodd = -1,
			posmodd = 1,
		},
	},
    ["ins2_br_supp_338"] = {
        name = ".338 Lapua Magnum Suppressor",
        desc = "A suppressor for .338 Lapua Magnum weapons.",
        price = 24800,--750,
        model = "models/Items/BoxMRounds.mdl",
        width = 2,
        height = 1,
		flag = "s",
        weight = 0.7,
        cat = 1,
        attID = "ins2_br_supp_338",
		expand = {
			--width = x, add right == 1, 0; add left == 1, -1;
			--			remove right == -1, 0; remove left == -1, 1
			--height = y, same as above but instead of left its down, and right is up
			wh = "w",
			sizemod = 1,
			posmod = -1,
			--used for removing
			sizemodd = -1,
			posmodd = 1,
		},
    },
    ["ins2_fg_grip"] = {
        name = "Fore Grip",
        desc = "A foregrip rail attachment.",
        price = 2500,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
		flag = "k",
        weight = 0.08,
        cat = 8,
        attID = "ins2_fg_grip",
	},
	--[[
    ["ins2_si_eotech_gits"] = {
        name = "EOTech 2552 Sight", --1x
        desc = "A EOTech sight. Actual model may vary depending on weapon.",
        price = 60,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
		flag = "4",
        weight = 0.65,
        cat = 7,
        attID = "ins2_si_eotech_gits",
    },
    ["ins2_si_kobra_gits"] = {
        name = "EKP-13-05 Kobra Sight", --1x
        desc = "A Kobra sight. Actual model may vary depending on weapon.",
        price = 650,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
		flag = "4",
        weight = 0.9,
        cat = 7,
        attID = "ins2_si_kobra_gits",
    },
    ["ins2_si_rds_gits"] = {
        name = "Aimpoint CompM9X Sight", --1x
        desc = "An Aimpoint sight. Actual model may vary depending on weapon.",
        price = 750,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
		flag = "4",
        weight = 0.65,
        cat = 7,
        attID = "ins2_si_rds_gits",
    },
    ["ins2_si_2xrds_gits"] = {
        name = "Aimpoint CompM9X 2X Sight", --2x
        desc = "An Aimpoint sight with magnifier. May also be an ACOG depending on weapon.",
        price = 1100,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
		flag = "4",
        weight = 1,
        cat = 7,
        attID = "ins2_si_2xrds_gits",
    },]]---[[
    ["ins2_si_eotech"] = {
        name = "EOTech 552 Sight", --1x
        desc = "",
        price = 5500,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
        weight = 0.3,
		flag = "l",
        cat = 7,
        attID = "ins2_si_eotech",
    },
    ["ins2_si_eotech_blitz"] = {
        name = "EOTech Holo-RDS", --1x
        desc = "",
        price = 6000,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
        weight = 0.3,
		flag = "l",
        cat = 7,
        attID = "ins2_si_eotech_blitz",
    },
    ["ins2_si_kobra"] = {
        name = "Kobra Sight", --1x
        desc = "",
        price = 4750,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
        weight = 0.4,
		flag = "l",
        cat = 7,
        attID = "ins2_si_kobra",
    },
    ["ins2_si_kobra_blitz"] = {
        name = "CMore RDS Sight", --1x
        desc = "",
        price = 5950,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
        weight = 0.4,
		flag = "l",
        cat = 7,
        attID = "ins2_si_kobra_blitz",
    },
    ["ins2_si_kobra_blitz2"] = {
        name = "Low Profile Kobra Sight", --1x
        desc = "",
        price = 4850,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
        weight = 0.4,
		flag = "l",
        cat = 7,
        attID = "ins2_si_kobra_blitz2",
    },
    ["ins2_si_kobra_blitz3"] = {
        name = "OKP-7 Sight", --1x
        desc = "",
        price = 4950,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
        weight = 0.4,
		flag = "l",
        cat = 7,
        attID = "ins2_si_kobra_blitz3",
    },
    ["ins2_si_rds"] = {
        name = "Aimpoint CompM2 Sight", --1x
        desc = "",
        price = 5300,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
        weight = 0.21,
		flag = "l",
        cat = 7,
        attID = "ins2_si_rds",
    },
    ["ins2_si_rds_blitz"] = {
        name = "Aimpoint CompM4s Sight", --1x
        desc = "",
        price = 5500,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
        weight = 0.21,
		flag = "l",
        cat = 7,
        attID = "ins2_si_rds_blitz",
    },
    ["ins2_si_rds_blitz2"] = {
        name = "MWR RDS? Sight", --1x
        desc = "",
        price = 5200,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
        weight = 0.21,
		flag = "l",
        cat = 7,
        attID = "ins2_si_rds_blitz2",
    },
    ["ins2_si_2xrds"] = {
        name = "Aimpoint CompM2 2X Sight", --2x
        desc = "",
        price = 9700,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
        weight = 0.4,
		flag = "l",
        cat = 7,
        attID = "ins2_si_2xrds",
    },--]]
    ["ins2_si_mx4"] = {
        name = "MX4 Scope", --8.7x
        desc = "A sniper scope.",
        price = 15200,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
        weight = 0.62,
		flag = "b",
        cat = 7,
        attID = "ins2_si_mx4",
    },
    ["ins2_si_c79"] = {
        name = "C79 Elcan Scope", --3.4x
        desc = "A telescopic sight.",
        price = 11850,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
        weight = 0.69,
		flag = "b",
        cat = 7,
        attID = "ins2_si_c79",
    },
    ["ins2_si_mosin"] = {
        name = "Mosin Scope", --7x
        desc = "A russian sniper scope.",
        price = 13650,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
		flag = "b",
        weight = 0.4,
        cat = 7,
        attID = "ins2_si_mosin",
    },
    ["ins2_si_po4x"] = {
        name = "PO 4x24P Scope", --4x
        desc = "A russian scope.",
        price = 10480,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
		flag = "b",
        weight = 0.6,
        cat = 7,
        attID = "ins2_si_po4x",
	},
	--[[
    ["ins2_si_po4x_gits"] = {
        name = "P8x24 Scope", --4x
        desc = "A large scope with 4x magnification. Fairly weird to be honest.",
        price = 1400,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
		flag = "4",
        weight = 1.5,
        cat = 7,
        attID = "ins2_si_po4x_gits",
	},
	]]
    --[[["specialatt_biolock"] = {
        name = "Portable Biolock", --4x
        desc = "A portable biolock. Cannot be unattached.",
        price = 250,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
		flag = "4",
        weight = 1.5,
        cat = 99,
		attID = "biofake",
		specialAtt = function(self, target)
			
			target:setData("biolock", true)
		end
    },--[[
    ["tfa_ins2_si_tiggsmatch"] = {
        name = "USP Match Compensator",
        desc = "",
        price = 200,
        model = "models/Items/BoxMRounds.mdl",
        width = 1,
        height = 1,
        weight = 0.25,
        cat = 8,
        attID = "tfa_ins2_si_tiggsmatch",
    },    ]]
}
