ITEM.name = "M67 Grenade" --tier 4 grenade
ITEM.desc = "A fragmentation grenade. Has a medium-sized blast radius and a 3 second timer."
ITEM.price = 5289
ITEM.model = "models/eft_grenades/grenade m67.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 0.2
ITEM.flag = "3"
ITEM.category = "Weapons - Grenades"
ITEM.class = "sky_g_frag_m67"
ITEM.weaponCategory = "grenade"
