ITEM.name = "Smoke Grenade" --tier 4 grenade
ITEM.desc = "A smoke grenade."
ITEM.price = 2550
ITEM.model = "models/weapons/w_eq_smokegrenade.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 0.2
ITEM.flag = "2"
ITEM.category = "Weapons - Grenades"
ITEM.class = "sky_g_smoke"
ITEM.weaponCategory = "grenade"
