ITEM.name = "Hatchet" --tier 1 melee
ITEM.desc = "A small wooden hatchet."
ITEM.price = 900
ITEM.model = "models/weapons/tfa_nmrih/w_me_hatchet.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 1.04
ITEM.flag = "1"
ITEM.category = "Weapons - Melees"
ITEM.class = "sky_m_nmrih_hatchet"
ITEM.weaponCategory = "melee"
