ITEM.name = "Zarya Flash Grenade" --tier 4 grenade
ITEM.desc = "A flashbang. Has a 2 second timer."
ITEM.price = 3300
ITEM.model = "models/eft_grenades/flash grenade zarya.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 0.25
ITEM.flag = "2"
ITEM.category = "Weapons - Grenades"
ITEM.class = "sky_g_flash_zarya"
ITEM.weaponCategory = "grenade"
