ITEM.name = "Fire Axe" --tier 1 melee
ITEM.desc = "A metal fire axe."
ITEM.price = 3000
ITEM.model = "models/weapons/tfa_nmrih/w_me_axe_fire.mdl"
ITEM.width = 1
ITEM.height = 4
ITEM.weight = 3
ITEM.flag = "1"
ITEM.category = "Weapons - Melees"
ITEM.class = "sky_m_nmrih_fireaxe"
ITEM.weaponCategory = "melee"
