ITEM.name = "Plastic Baton" --tier 1 melee
ITEM.desc = "A black plastic baton."
ITEM.price = 1000
ITEM.model = "models/mosi/fallout4/props/weapons/melee/baton.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 0.58
ITEM.flag = "1"
ITEM.category = "Weapons - Melees"
ITEM.class = "sky_m_nmrih_f4baton"
ITEM.weaponCategory = "melee"
