ITEM.name = "Padded Cloth"
ITEM.desc = "A bit of padded cloth for crafting."
ITEM.model = "models/wick/wrbstalker/anomaly/items/wick_prt_o_fabrics_2.mdl"
ITEM.category = "Components"
ITEM.weight = 0.08
ITEM.price = 350
ITEM.flag = "J"
ITEM.countMax = 15
ITEM.maxQuantity = 15