ITEM.name = "Scrap of Cloth"
ITEM.desc = "A bit of cloth for crafting."
ITEM.model = "models/wick/wrbstalker/anomaly/items/wick_prt_o_fabrics_1.mdl"
ITEM.category = "Components"
ITEM.weight = 0.01
ITEM.price = 150
ITEM.flag = "J"
ITEM.countMax = 25
ITEM.maxQuantity = 25