ITEM.name = "Jar of Antiseptic"
ITEM.desc = "A jar of antiseptic for crafting."
ITEM.model = "models/fallout/components/jar.mdl"
ITEM.skin = 4
ITEM.category = "Components"
ITEM.weight = 0.4
ITEM.price = 900
ITEM.flag = "J"
ITEM.countMax = 5
ITEM.maxQuantity = 5