ITEM.name = "Car Battery"
ITEM.desc = "A dead car battery."
ITEM.model = "models/Items/car_battery01.mdl"
ITEM.category = "Junk"
ITEM.weight = 9
ITEM.width = 2
ITEM.height = 2
ITEM.price = 2000
ITEM.flag = "J"
ITEM.permit = "elec"