
on:
  workflow_dispatch
name: 🧳 Addon Deploy
jobs:
  gamemode-deploy:
    name: 🎉 Addon Update 🎉
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code  (Addon) 
      uses: actions/checkout@v2
    
    - name: 📂 Sync Addons
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: 216.52.25.77
        port: 8822
        username: nathan6
        password: ${{ secrets.ftp_password }}
        server-dir: /216.52.25.77_27055/garrysmod/
        exclude: .git*
          - **.git*
          - .git*/**
          -  **/.git*/**
          - assets/
          - .glualint.json
          - nutscript/
          - stalker/
          - README.md